package be.winnetrie.mod.simpleserverutilities.onboarding;

import java.util.ArrayList;import java.util.List;import java.util.UUID;import com.google.gson.Gson;import com.google.gson.GsonBuilder;import com.google.gson.reflect.TypeToken;
import be.winnetrie.mod.simpleserverutilities.SimpleServerUtilities;import be.winnetrie.mod.simpleserverutilities.core.module.SsuModuleAccess;import be.winnetrie.mod.simpleserverutilities.network.OnboardingAdminDataPayload;import be.winnetrie.mod.simpleserverutilities.network.OnboardingAdminRequestPayload;import be.winnetrie.mod.simpleserverutilities.network.OnboardingAdminSavePayload;import be.winnetrie.mod.simpleserverutilities.permission.PermissionKeys;import be.winnetrie.mod.simpleserverutilities.permission.PermissionService;import be.winnetrie.mod.simpleserverutilities.spawn.ServerSpawn;
import net.minecraft.server.level.ServerPlayer;import net.neoforged.neoforge.network.PacketDistributor;import net.neoforged.neoforge.network.handling.IPayloadContext;

/** Compact admin boundary for onboarding, server spawn and lobby spawn. */
public final class OnboardingService{
 private static final Gson GSON=new GsonBuilder().create();private static final java.lang.reflect.Type PAGE_LIST=new TypeToken<List<String>>(){}.getType();private OnboardingService(){}
 public static void handleRequest(OnboardingAdminRequestPayload p,IPayloadContext c){
        if (!be.winnetrie.mod.simpleserverutilities.core.module.SsuModuleAccess.active("onboarding")) return;if(c.player() instanceof ServerPlayer player)send(player,p.requestId(),"",false);}
 public static void handleSave(OnboardingAdminSavePayload p,IPayloadContext c){
        if (!be.winnetrie.mod.simpleserverutilities.core.module.SsuModuleAccess.active("onboarding")) return;if(!(c.player() instanceof ServerPlayer player))return;if(!canAdmin(player)){send(player,p.requestId(),"Onboarding administration denied.",true);return;}String notice;boolean error=false;try{switch(p.action().trim().toLowerCase(java.util.Locale.ROOT)){
  case "save"->{OnboardingSettings s=new OnboardingSettings();s.enabled=p.enabled();s.requireRules=p.requireRules();s.introductionSkippable=p.skippable();s.welcomeFireworks=p.fireworks();s.welcomeTitle=p.welcomeTitle();s.welcomeSubtitle=p.welcomeSubtitle();s.rules=p.rules();List<String> pages=GSON.fromJson(p.pagesJson(),PAGE_LIST);s.introductionPages=pages==null?new ArrayList<>():new ArrayList<>(pages);SimpleServerUtilities.ONBOARDING.updateSettings(s);notice="Onboarding settings saved.";}
  case "set_server_spawn"->{SimpleServerUtilities.SERVER_SPAWN.set(player);notice="Server respawn fallback set to your current position.";}
  case "clear_server_spawn"->{SimpleServerUtilities.SERVER_SPAWN.clear();notice="Server spawn cleared. Vanilla world spawn is now the final fallback.";}
  case "set_lobby_spawn"->{SimpleServerUtilities.SERVER_SPAWN.setLobby(player);notice="Lobby spawn set to your current position.";}
  case "clear_lobby_spawn"->{SimpleServerUtilities.SERVER_SPAWN.clearLobby();notice="Lobby spawn cleared.";}
  case "reset_player"->{UUID id=resolve(player,p.target());if(id==null)throw new IllegalArgumentException("Player name or UUID was not found.");ServerPlayer online=player.level().getServer().getPlayerList().getPlayer(id);String name=online==null?p.target():online.getName().getString();SimpleServerUtilities.ONBOARDING.reset(id,name);if(online!=null)SimpleServerUtilities.ONBOARDING.onLogin(online);notice="Onboarding reset for "+name+".";}
  case "complete_player"->{UUID id=resolve(player,p.target());if(id==null)throw new IllegalArgumentException("Player name or UUID was not found.");ServerPlayer online=player.level().getServer().getPlayerList().getPlayer(id);String name=online==null?p.target():online.getName().getString();SimpleServerUtilities.ONBOARDING.markCompleted(id,name);notice="Onboarding marked complete for "+name+".";}
  default->throw new IllegalArgumentException("Unknown onboarding action.");}
 }catch(Exception ex){notice=ex.getMessage()==null?"Onboarding action failed safely.":ex.getMessage();error=true;}if(!error&&SsuModuleAccess.active("server_operations"))SimpleServerUtilities.SERVER_OPERATIONS.audit(player,"onboarding."+p.action(),p.target(),notice);send(player,p.requestId(),notice,error);}
 private static void send(ServerPlayer player,long request,String notice,boolean error){if(!canAdmin(player)){PacketDistributor.sendToPlayer(player,new OnboardingAdminDataPayload(false,false,false,false,"","","","[]",false,"",false,"","Onboarding administration denied.",true,request));return;}OnboardingSettings s=SimpleServerUtilities.ONBOARDING.settingsCopy();ServerSpawn spawn=SimpleServerUtilities.SERVER_SPAWN.get();ServerSpawn lobby=SimpleServerUtilities.SERVER_SPAWN.getLobby();PacketDistributor.sendToPlayer(player,new OnboardingAdminDataPayload(s.enabled,s.requireRules,s.introductionSkippable,s.welcomeFireworks,s.welcomeTitle,s.welcomeSubtitle,s.rules,GSON.toJson(s.introductionPages),spawn!=null,summary(spawn),lobby!=null,summary(lobby),notice,error,request));}
 private static String summary(ServerSpawn s){return s==null?"Not set":s.getDimension()+" @ "+String.format(java.util.Locale.ROOT,"%.1f, %.1f, %.1f",s.getX(),s.getY(),s.getZ());}
 private static boolean canAdmin(ServerPlayer p){return PermissionService.isAdmin(p)&&PermissionService.getBoolean(p,PermissionKeys.ONBOARDING_ADMIN,false);}
 private static UUID resolve(ServerPlayer actor,String raw){if(raw==null||raw.isBlank())return null;String query=raw.trim();try{return UUID.fromString(query);}catch(IllegalArgumentException ignored){}ServerPlayer online=actor.level().getServer().getPlayerList().getPlayerByName(query);if(online!=null)return online.getUUID();if(SsuModuleAccess.active("moderation"))return SimpleServerUtilities.MODERATION.resolvePlayer(query);if(SsuModuleAccess.active("permissions"))return SimpleServerUtilities.PERMISSIONS.findKnownPlayerId(query);return null;}
}
