package be.winnetrie.mod.simpleserverutilities.client.gui;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import be.winnetrie.mod.simpleserverutilities.content.ContentAction;
import be.winnetrie.mod.simpleserverutilities.content.ContentCondition;
import be.winnetrie.mod.simpleserverutilities.dungeon.DungeonArenaDefinition;
import be.winnetrie.mod.simpleserverutilities.dungeon.DungeonCheckpointDefinition;
import be.winnetrie.mod.simpleserverutilities.dungeon.DungeonDefinition;
import be.winnetrie.mod.simpleserverutilities.dungeon.DungeonLocation;
import be.winnetrie.mod.simpleserverutilities.dungeon.DungeonStageDefinition;
import be.winnetrie.mod.simpleserverutilities.network.DungeonEditorOpenPayload;
import be.winnetrie.mod.simpleserverutilities.network.DungeonEditorResultPayload;
import be.winnetrie.mod.simpleserverutilities.network.DungeonEditorSubmitPayload;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.components.MultiLineEditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.client.network.ClientPacketDistributor;

/** Structured editor for dungeon lifecycle, arenas, checkpoints, stages, requirements and rewards. */
public final class DungeonEditorScreen extends Screen {
    private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();
    private static final int W=790,H=520,PANEL=0xF0161D25,BORDER=0xFF586978,TEXT=0xFFF3F5F7,MUTED=0xFFAAB5BE,GOOD=0xFF83E39A,ERROR=0xFFFF8585;
    private final DungeonEditorOpenPayload initial;private final Screen parent;private DungeonDefinition draft;private int page,arenaIndex,checkpointIndex,stageIndex;private int rewardGroup,rewardIndex=-1;private long nextRequestId=1L;private boolean awaiting;private String notice="";private boolean noticeError;
    private EditBox id,name,icon,minPlayers,maxPlayers,lives,countdown,duration,postRun;private MultiLineEditBox description;private String descriptionValue="";private Button enabledButton,automaticButton,lateJoinButton;private boolean enabled,automaticStart,allowLateJoin;
    private EditBox arenaId,arenaName,regionId;private Button arenaEnabledButton,arenaResetButton;private boolean arenaEnabled,arenaReset;private EditBox lobbyDimension,lobbyX,lobbyY,lobbyZ,lobbyYaw,lobbyPitch,startDimension,startX,startY,startZ,startYaw,startPitch,spectatorDimension,spectatorX,spectatorY,spectatorZ,spectatorYaw,spectatorPitch;
    private EditBox checkpointId,checkpointName,checkpointDimension,checkpointX,checkpointY,checkpointZ,checkpointYaw,checkpointPitch;
    private EditBox stageId,stageName,stageType,stageSubject,stageCheckpoint,stageRequired,stageDuration;private MultiLineEditBox stageDescription;private String stageDescriptionValue="";
    private EditBox conditionType,conditionParameters,rewardType,rewardParameters;

    public DungeonEditorScreen(DungeonEditorOpenPayload initial,Screen parent){super(Component.literal("Dungeon Editor"));this.initial=initial;this.parent=parent;try{draft=GSON.fromJson(initial.definitionJson(),DungeonDefinition.class);}catch(RuntimeException ignored){draft=new DungeonDefinition();}ensureDraft();}

    private void ensureDraft(){if(draft==null)draft=new DungeonDefinition();if(draft.prerequisites==null)draft.prerequisites=new ContentCondition();if(draft.participationRewards==null)draft.participationRewards=new ArrayList<>();if(draft.completionRewards==null)draft.completionRewards=new ArrayList<>();if(draft.failureRewards==null)draft.failureRewards=new ArrayList<>();if(draft.arenas==null)draft.arenas=new ArrayList<>();if(draft.arenas.isEmpty())draft.arenas.add(new DungeonArenaDefinition());if(draft.stages==null)draft.stages=new ArrayList<>();if(draft.stages.isEmpty())draft.stages.add(new DungeonStageDefinition());arenaIndex=clampIndex(arenaIndex,draft.arenas);DungeonArenaDefinition arena=draft.arenas.get(arenaIndex);if(arena.checkpoints==null)arena.checkpoints=new ArrayList<>();if(arena.checkpoints.isEmpty())arena.checkpoints.add(new DungeonCheckpointDefinition());checkpointIndex=clampIndex(checkpointIndex,arena.checkpoints);stageIndex=clampIndex(stageIndex,draft.stages);rewardIndex=normalizeIndex(rewardIndex,rewardList());}
    private static int clampIndex(int index,List<?> list){return Math.max(0,Math.min(index,list.size()-1));}private static int normalizeIndex(int index,List<?> list){if(list==null||list.isEmpty())return-1;return Math.max(0,Math.min(index<0?0:index,list.size()-1));}

    @Override protected void init(){ensureDraft();int x=px(),y=py();addRenderableWidget(Button.builder(Component.literal("General"),i->switchPage(0)).bounds(x+16,y+12,88,20).build()).active=page!=0;addRenderableWidget(Button.builder(Component.literal("Arenas"),i->switchPage(1)).bounds(x+110,y+12,88,20).build()).active=page!=1;addRenderableWidget(Button.builder(Component.literal("Stages"),i->switchPage(2)).bounds(x+204,y+12,88,20).build()).active=page!=2;addRenderableWidget(Button.builder(Component.literal("Requirements & Rewards"),i->switchPage(3)).bounds(x+298,y+12,176,20).build()).active=page!=3;if(page==0)initGeneral(x,y);else if(page==1)initArena(x,y);else if(page==2)initStage(x,y);else initRewards(x,y);addRenderableWidget(Button.builder(Component.literal("Cancel"),i->onClose()).bounds(x+16,y+H-32,90,20).build());Button save=addRenderableWidget(Button.builder(Component.literal("Save dungeon"),i->submit()).bounds(x+W-132,y+H-32,116,20).build());save.active=!awaiting;}

    private void initGeneral(int x,int y){id=field(x+16,y+50,180,64,"Dungeon ID",draft.id);name=field(x+206,y+50,250,128,"Display name",draft.displayName);icon=field(x+466,y+50,308,128,"Icon item",draft.iconItem);descriptionValue=draft.description==null?"":draft.description;description=MultiLineEditBox.builder().setX(x+16).setY(y+84).setPlaceholder(Component.literal("Description")).setShowBackground(true).setShowDecorations(true).build(font,758,86,Component.literal("Description"));description.setCharacterLimit(8192);description.setLineLimit(64);description.setValue(descriptionValue);description.setValueListener(v->descriptionValue=v);addRenderableWidget(description);enabled=draft.enabled;automaticStart=draft.automaticStart;allowLateJoin=draft.allowLateJoin;enabledButton=toggle(x+16,y+182,132,()->{enabled=!enabled;updateLabels();});automaticButton=toggle(x+154,y+182,152,()->{automaticStart=!automaticStart;updateLabels();});lateJoinButton=toggle(x+312,y+182,138,()->{allowLateJoin=!allowLateJoin;updateLabels();});minPlayers=field(x+16,y+222,108,4,"Minimum players",Integer.toString(draft.minPlayers));maxPlayers=field(x+134,y+222,108,4,"Maximum players",Integer.toString(draft.maxPlayers));lives=field(x+252,y+222,108,4,"Lives (0=∞)",Integer.toString(draft.livesPerPlayer));countdown=field(x+16,y+260,126,6,"Countdown seconds",Integer.toString(draft.countdownSeconds));duration=field(x+152,y+260,126,8,"Time limit seconds",Integer.toString(draft.timeLimitSeconds));postRun=field(x+288,y+260,126,6,"Post-run seconds",Integer.toString(draft.postRunSeconds));updateLabels();}

    private void initArena(int x,int y){DungeonArenaDefinition arena=arena();addRenderableWidget(Button.builder(Component.literal("‹"),i->switchArena(-1)).bounds(x+16,y+48,32,20).build());addRenderableWidget(Button.builder(Component.literal("›"),i->switchArena(1)).bounds(x+52,y+48,32,20).build());addRenderableWidget(Button.builder(Component.literal("Add arena"),i->addArena()).bounds(x+94,y+48,92,20).build());addRenderableWidget(Button.builder(Component.literal("Delete arena"),i->deleteArena()).bounds(x+192,y+48,100,20).build());arenaId=field(x+16,y+82,170,64,"Arena ID",arena.id);arenaName=field(x+196,y+82,220,128,"Arena name",arena.displayName);regionId=field(x+426,y+82,190,128,"Required SSU region",arena.regionId);arenaEnabled=arena.enabled;arenaReset=arena.resetRegionAfterRun;arenaEnabledButton=toggle(x+626,y+82,148,()->{arenaEnabled=!arenaEnabled;updateLabels();});arenaResetButton=toggle(x+626,y+112,148,()->{arenaReset=!arenaReset;updateLabels();});locationFields(x+16,y+132,"Lobby",arena.lobby,0);useCurrent(x+676,y+154,0);locationFields(x+16,y+196,"Start",arena.start,1);useCurrent(x+676,y+218,1);locationFields(x+16,y+260,"Spectator",arena.spectator,2);useCurrent(x+676,y+282,2);addRenderableWidget(Button.builder(Component.literal("‹"),i->switchCheckpoint(-1)).bounds(x+16,y+340,32,20).build());addRenderableWidget(Button.builder(Component.literal("›"),i->switchCheckpoint(1)).bounds(x+52,y+340,32,20).build());addRenderableWidget(Button.builder(Component.literal("Add checkpoint"),i->addCheckpoint()).bounds(x+94,y+340,112,20).build());addRenderableWidget(Button.builder(Component.literal("Delete checkpoint"),i->deleteCheckpoint()).bounds(x+212,y+340,126,20).build());DungeonCheckpointDefinition cp=checkpoint();checkpointId=field(x+16,y+370,170,64,"Checkpoint ID",cp.id);checkpointName=field(x+196,y+370,220,128,"Checkpoint name",cp.displayName);checkpointLocationFields(x+16,y+404,cp.location);addRenderableWidget(Button.builder(Component.literal("Use current"),i->fillCurrent(checkpointDimension,checkpointX,checkpointY,checkpointZ,checkpointYaw,checkpointPitch)).bounds(x+676,y+426,98,20).build());updateLabels();}

    private void locationFields(int x,int y,String label,DungeonLocation loc,int kind){EditBox d=field(x,y+22,190,128,label+" dimension",loc.dimension),fx=field(x+200,y+22,78,24,"X",number(loc.x)),fy=field(x+288,y+22,78,24,"Y",number(loc.y)),fz=field(x+376,y+22,78,24,"Z",number(loc.z)),fyaw=field(x+464,y+22,86,16,"Yaw",number(loc.yaw)),fpitch=field(x+560,y+22,86,16,"Pitch",number(loc.pitch));if(kind==0){lobbyDimension=d;lobbyX=fx;lobbyY=fy;lobbyZ=fz;lobbyYaw=fyaw;lobbyPitch=fpitch;}else if(kind==1){startDimension=d;startX=fx;startY=fy;startZ=fz;startYaw=fyaw;startPitch=fpitch;}else{spectatorDimension=d;spectatorX=fx;spectatorY=fy;spectatorZ=fz;spectatorYaw=fyaw;spectatorPitch=fpitch;}}
    private void useCurrent(int x,int y,int kind){addRenderableWidget(Button.builder(Component.literal("Use current"),i->{if(kind==0)fillCurrent(lobbyDimension,lobbyX,lobbyY,lobbyZ,lobbyYaw,lobbyPitch);else if(kind==1)fillCurrent(startDimension,startX,startY,startZ,startYaw,startPitch);else fillCurrent(spectatorDimension,spectatorX,spectatorY,spectatorZ,spectatorYaw,spectatorPitch);}).bounds(x,y,98,20).build());}
    private void checkpointLocationFields(int x,int y,DungeonLocation loc){checkpointDimension=field(x,y+22,190,128,"Checkpoint dimension",loc.dimension);checkpointX=field(x+200,y+22,78,24,"X",number(loc.x));checkpointY=field(x+288,y+22,78,24,"Y",number(loc.y));checkpointZ=field(x+376,y+22,78,24,"Z",number(loc.z));checkpointYaw=field(x+464,y+22,86,16,"Yaw",number(loc.yaw));checkpointPitch=field(x+560,y+22,86,16,"Pitch",number(loc.pitch));}

    private void initStage(int x,int y){DungeonStageDefinition stage=stage();addRenderableWidget(Button.builder(Component.literal("‹"),i->switchStage(-1)).bounds(x+16,y+48,32,20).build());addRenderableWidget(Button.builder(Component.literal("›"),i->switchStage(1)).bounds(x+52,y+48,32,20).build());addRenderableWidget(Button.builder(Component.literal("Add stage"),i->addStage()).bounds(x+94,y+48,92,20).build());addRenderableWidget(Button.builder(Component.literal("Delete stage"),i->deleteStage()).bounds(x+192,y+48,100,20).build());stageId=field(x+16,y+84,170,64,"Stage ID",stage.id);stageName=field(x+196,y+84,250,128,"Stage name",stage.displayName);stageType=field(x+456,y+84,190,32,"manual / kill_count / reach_checkpoint / survive_seconds",stage.type);stageSubject=field(x+16,y+122,220,128,"Kill subject (* or entity ID)",stage.subject);stageCheckpoint=field(x+246,y+122,200,64,"Checkpoint ID",stage.checkpointId);stageRequired=field(x+456,y+122,110,16,"Required amount",Long.toString(stage.requiredAmount));stageDuration=field(x+576,y+122,110,8,"Duration seconds",Integer.toString(stage.durationSeconds));stageDescriptionValue=stage.description==null?"":stage.description;stageDescription=MultiLineEditBox.builder().setX(x+16).setY(y+166).setPlaceholder(Component.literal("Stage description")).setShowBackground(true).setShowDecorations(true).build(font,758,120,Component.literal("Stage description"));stageDescription.setCharacterLimit(2048);stageDescription.setLineLimit(32);stageDescription.setValue(stageDescriptionValue);stageDescription.setValueListener(v->stageDescriptionValue=v);addRenderableWidget(stageDescription);}

    private void initRewards(int x,int y){conditionType=field(x+16,y+58,220,64,"Condition type",draft.prerequisites.type());conditionParameters=field(x+246,y+58,528,2048,"Condition parameters: key=value; key=value",parameters(draft.prerequisites.parameters()));addRenderableWidget(Button.builder(Component.literal("Participation"),i->switchRewardGroup(0)).bounds(x+16,y+112,120,20).build()).active=rewardGroup!=0;addRenderableWidget(Button.builder(Component.literal("Completion"),i->switchRewardGroup(1)).bounds(x+142,y+112,120,20).build()).active=rewardGroup!=1;addRenderableWidget(Button.builder(Component.literal("Failure"),i->switchRewardGroup(2)).bounds(x+268,y+112,120,20).build()).active=rewardGroup!=2;addRenderableWidget(Button.builder(Component.literal("‹"),i->switchReward(-1)).bounds(x+16,y+150,32,20).build());addRenderableWidget(Button.builder(Component.literal("›"),i->switchReward(1)).bounds(x+52,y+150,32,20).build());addRenderableWidget(Button.builder(Component.literal("Add reward"),i->addReward()).bounds(x+94,y+150,92,20).build());addRenderableWidget(Button.builder(Component.literal("Delete reward"),i->deleteReward()).bounds(x+192,y+150,110,20).build());ContentAction reward=reward();rewardType=field(x+16,y+184,220,64,"Reward action type",reward==null?"":reward.type());rewardParameters=field(x+246,y+184,528,2048,"Reward parameters: key=value; key=value",reward==null?"":parameters(reward.parameters()));}

    private void saveCurrent(){ensureDraft();if(page==0&&id!=null){draft.id=id.getValue().trim();draft.displayName=name.getValue().trim();draft.iconItem=icon.getValue().trim();draft.description=descriptionValue;draft.enabled=enabled;draft.automaticStart=automaticStart;draft.allowLateJoin=allowLateJoin;draft.minPlayers=parseInt(minPlayers.getValue(),1);draft.maxPlayers=parseInt(maxPlayers.getValue(),4);draft.livesPerPlayer=parseInt(lives.getValue(),3);draft.countdownSeconds=parseInt(countdown.getValue(),10);draft.timeLimitSeconds=parseInt(duration.getValue(),1800);draft.postRunSeconds=parseInt(postRun.getValue(),8);}else if(page==1&&arenaId!=null){DungeonArenaDefinition a=arena();a.id=arenaId.getValue().trim();a.displayName=arenaName.getValue().trim();a.regionId=regionId.getValue().trim();a.enabled=arenaEnabled;a.resetRegionAfterRun=arenaReset;a.lobby=readLocation(lobbyDimension,lobbyX,lobbyY,lobbyZ,lobbyYaw,lobbyPitch);a.start=readLocation(startDimension,startX,startY,startZ,startYaw,startPitch);a.spectator=readLocation(spectatorDimension,spectatorX,spectatorY,spectatorZ,spectatorYaw,spectatorPitch);DungeonCheckpointDefinition cp=checkpoint();cp.id=checkpointId.getValue().trim();cp.displayName=checkpointName.getValue().trim();cp.location=readLocation(checkpointDimension,checkpointX,checkpointY,checkpointZ,checkpointYaw,checkpointPitch);}else if(page==2&&stageId!=null){DungeonStageDefinition s=stage();s.id=stageId.getValue().trim();s.displayName=stageName.getValue().trim();s.type=stageType.getValue().trim();s.subject=stageSubject.getValue().trim();s.checkpointId=stageCheckpoint.getValue().trim();s.requiredAmount=parseLong(stageRequired.getValue(),1L);s.durationSeconds=parseInt(stageDuration.getValue(),30);s.description=stageDescriptionValue;}else if(page==3&&conditionType!=null){String type=conditionType.getValue().trim();if(type.isBlank())type="always";draft.prerequisites=new ContentCondition(type,parseParameters(conditionParameters.getValue()),draft.prerequisites.children());List<ContentAction> list=rewardList();int index=rewardIndex;String typeValue=rewardType.getValue().trim();if(index>=0){if(typeValue.isBlank()){list.remove(index);rewardIndex=normalizeIndex(index,list);}else list.set(index,new ContentAction(typeValue,parseParameters(rewardParameters.getValue())));}else if(!typeValue.isBlank()){list.add(new ContentAction(typeValue,parseParameters(rewardParameters.getValue())));rewardIndex=list.size()-1;}}}

    private void fillCurrent(EditBox dimension,EditBox x,EditBox y,EditBox z,EditBox yaw,EditBox pitch){if(minecraft==null||minecraft.player==null)return;dimension.setValue(minecraft.player.level().dimension().identifier().toString());x.setValue(number(minecraft.player.getX()));y.setValue(number(minecraft.player.getY()));z.setValue(number(minecraft.player.getZ()));yaw.setValue(number(minecraft.player.getYRot()));pitch.setValue(number(minecraft.player.getXRot()));}
    private DungeonLocation readLocation(EditBox d,EditBox x,EditBox y,EditBox z,EditBox yaw,EditBox pitch){return new DungeonLocation(d.getValue().trim(),parseDouble(x.getValue(),0),parseDouble(y.getValue(),64),parseDouble(z.getValue(),0),(float)parseDouble(yaw.getValue(),0),(float)parseDouble(pitch.getValue(),0));}
    private void switchPage(int target){saveCurrent();page=target;rebuildWidgets();}private void switchArena(int delta){saveCurrent();arenaIndex=Math.floorMod(arenaIndex+delta,draft.arenas.size());checkpointIndex=0;rebuildWidgets();}private void addArena(){saveCurrent();if(draft.arenas.size()>=DungeonDefinition.MAX_ARENAS){setNotice("Maximum arenas reached.",true);return;}DungeonArenaDefinition a=new DungeonArenaDefinition();a.id="arena_"+(draft.arenas.size()+1);draft.arenas.add(a);arenaIndex=draft.arenas.size()-1;checkpointIndex=0;rebuildWidgets();}private void deleteArena(){saveCurrent();if(draft.arenas.size()<=1){setNotice("A dungeon needs at least one arena.",true);return;}draft.arenas.remove(arenaIndex);arenaIndex=Math.max(0,arenaIndex-1);checkpointIndex=0;rebuildWidgets();}
    private void switchCheckpoint(int delta){saveCurrent();checkpointIndex=Math.floorMod(checkpointIndex+delta,arena().checkpoints.size());rebuildWidgets();}private void addCheckpoint(){saveCurrent();if(arena().checkpoints.size()>=DungeonArenaDefinition.MAX_CHECKPOINTS){setNotice("Maximum checkpoints reached.",true);return;}DungeonCheckpointDefinition cp=new DungeonCheckpointDefinition();cp.id="checkpoint_"+(arena().checkpoints.size()+1);arena().checkpoints.add(cp);checkpointIndex=arena().checkpoints.size()-1;rebuildWidgets();}private void deleteCheckpoint(){saveCurrent();if(arena().checkpoints.size()<=1){setNotice("An arena needs at least one checkpoint entry.",true);return;}arena().checkpoints.remove(checkpointIndex);checkpointIndex=Math.max(0,checkpointIndex-1);rebuildWidgets();}
    private void switchStage(int delta){saveCurrent();stageIndex=Math.floorMod(stageIndex+delta,draft.stages.size());rebuildWidgets();}private void addStage(){saveCurrent();if(draft.stages.size()>=DungeonDefinition.MAX_STAGES){setNotice("Maximum stages reached.",true);return;}DungeonStageDefinition s=new DungeonStageDefinition();s.id="stage_"+(draft.stages.size()+1);draft.stages.add(s);stageIndex=draft.stages.size()-1;rebuildWidgets();}private void deleteStage(){saveCurrent();if(draft.stages.size()<=1){setNotice("Keep at least one stage; use manual type for a fully scripted dungeon.",true);return;}draft.stages.remove(stageIndex);stageIndex=Math.max(0,stageIndex-1);rebuildWidgets();}
    private void switchRewardGroup(int group){saveCurrent();rewardGroup=group;rewardIndex=normalizeIndex(rewardIndex,rewardList());rebuildWidgets();}private void switchReward(int delta){saveCurrent();List<ContentAction> list=rewardList();rewardIndex=list.isEmpty()?-1:Math.floorMod((rewardIndex<0?0:rewardIndex)+delta,list.size());rebuildWidgets();}private void addReward(){saveCurrent();List<ContentAction> list=rewardList();if(list.size()>=DungeonDefinition.MAX_REWARDS){setNotice("Maximum rewards reached.",true);return;}list.add(new ContentAction("set_player_flag",Map.of("key","dungeon_reward","value","true")));rewardIndex=list.size()-1;rebuildWidgets();}private void deleteReward(){saveCurrent();List<ContentAction> list=rewardList();if(rewardIndex<0){setNotice("No reward is selected.",true);return;}list.remove(rewardIndex);rewardIndex=normalizeIndex(rewardIndex,list);rebuildWidgets();}
    private DungeonArenaDefinition arena(){ensureDraft();return draft.arenas.get(arenaIndex);}private DungeonCheckpointDefinition checkpoint(){ensureDraft();return arena().checkpoints.get(checkpointIndex);}private DungeonStageDefinition stage(){ensureDraft();return draft.stages.get(stageIndex);}private List<ContentAction> rewardList(){return rewardGroup==1?draft.completionRewards:rewardGroup==2?draft.failureRewards:draft.participationRewards;}private ContentAction reward(){List<ContentAction> list=rewardList();return rewardIndex<0||rewardIndex>=list.size()?null:list.get(rewardIndex);}
    private void submit(){saveCurrent();try{draft.normalize();awaiting=true;long request=nextRequestId++;ClientPacketDistributor.sendToServer(new DungeonEditorSubmitPayload(initial.originalDungeonId(),GSON.toJson(draft),request));setNotice("Saving dungeon…",false);rebuildWidgets();}catch(RuntimeException exception){setNotice(exception.getMessage()==null?"Dungeon validation failed.":exception.getMessage(),true);}}
    public void accept(DungeonEditorResultPayload result){if(result==null)return;awaiting=false;nextRequestId=Math.max(nextRequestId,result.requestId()+1);setNotice(result.message(),!result.successful());if(result.successful()){if(minecraft!=null){minecraft.setScreenAndShow(parent);if(parent instanceof DungeonLobbyScreen lobby)lobby.refreshFromEditor();}}else rebuildWidgets();}
    private EditBox field(int x,int y,int w,int max,String hint,String value){EditBox box=new EditBox(font,x,y,w,20,Component.literal(hint));box.setHint(Component.literal(hint));box.setMaxLength(max);box.setValue(value==null?"":value);addRenderableWidget(box);return box;}private Button toggle(int x,int y,int w,Runnable action){return addRenderableWidget(Button.builder(Component.empty(),i->action.run()).bounds(x,y,w,20).build());}
    private void updateLabels(){if(enabledButton!=null)enabledButton.setMessage(Component.literal("Enabled: "+yes(enabled)));if(automaticButton!=null)automaticButton.setMessage(Component.literal("Auto start: "+yes(automaticStart)));if(lateJoinButton!=null)lateJoinButton.setMessage(Component.literal("Late join: "+yes(allowLateJoin)));if(arenaEnabledButton!=null)arenaEnabledButton.setMessage(Component.literal("Enabled: "+yes(arenaEnabled)));if(arenaResetButton!=null)arenaResetButton.setMessage(Component.literal("Reset region: "+yes(arenaReset)));}
    private static String yes(boolean v){return v?"Yes":"No";}private void setNotice(String m,boolean e){notice=m==null?"":m;noticeError=e;}private int px(){return(width-W)/2;}private int py(){return(height-H)/2;}@Override public void onClose(){if(minecraft!=null)minecraft.setScreenAndShow(parent);}@Override public boolean isPauseScreen(){return false;}
    @Override public void extractRenderState(GuiGraphicsExtractor g,int mouseX,int mouseY,float partialTick){int x=px(),y=py();g.fill(0,0,width,height,0xA5000000);g.fill(x,y,x+W,y+H,PANEL);g.outline(x,y,W,H,BORDER);g.text(font,"Dungeon Editor",x+500,y+18,TEXT,true);if(page==1){g.text(font,"Arena "+(arenaIndex+1)+" / "+draft.arenas.size(),x+310,y+54,MUTED,false);g.text(font,"Lobby",x+16,y+132,TEXT,true);g.text(font,"Start",x+16,y+196,TEXT,true);g.text(font,"Spectator",x+16,y+260,TEXT,true);g.text(font,"Checkpoint "+(checkpointIndex+1)+" / "+arena().checkpoints.size(),x+350,y+346,MUTED,false);}else if(page==2)g.text(font,"Stage "+(stageIndex+1)+" / "+draft.stages.size()+" • ordered execution",x+310,y+54,MUTED,false);else if(page==3){g.text(font,"Conditions and rewards use shared Content Core key=value parameters.",x+16,y+226,MUTED,false);g.text(font,"Reward group: "+(rewardGroup==1?"completion":rewardGroup==2?"failure":"participation")+" • reward "+(rewardIndex<0?0:rewardIndex+1)+" / "+rewardList().size(),x+16,y+246,MUTED,false);}if(!notice.isBlank())g.text(font,trim(notice,100),x+118,y+H-27,noticeError?ERROR:GOOD,false);super.extractRenderState(g,mouseX,mouseY,partialTick);}
    private static int parseInt(String raw,int fallback){try{return Integer.parseInt(raw.trim());}catch(RuntimeException ignored){return fallback;}}private static long parseLong(String raw,long fallback){try{return Long.parseLong(raw.trim());}catch(RuntimeException ignored){return fallback;}}private static double parseDouble(String raw,double fallback){try{return Double.parseDouble(raw.trim());}catch(RuntimeException ignored){return fallback;}}private static String number(double v){return Double.toString(v);}private static String parameters(Map<String,String> values){if(values==null||values.isEmpty())return"";StringBuilder out=new StringBuilder();values.forEach((k,v)->{if(!out.isEmpty())out.append("; ");out.append(k).append('=').append(v);});return out.toString();}private static Map<String,String> parseParameters(String raw){LinkedHashMap<String,String> result=new LinkedHashMap<>();if(raw==null||raw.isBlank())return result;for(String part:raw.split(";")){String value=part.trim();if(value.isBlank())continue;int split=value.indexOf('=');if(split<=0)throw new IllegalArgumentException("Parameters must use key=value separated by semicolons.");result.put(value.substring(0,split).trim(),value.substring(split+1).trim());}return result;}private static String trim(String value,int max){if(value==null)return"";return value.length()<=max?value:value.substring(0,Math.max(0,max-1))+"…";}
}
