package be.winnetrie.mod.simpleserverutilities.client.gui;

import java.util.List;
import be.winnetrie.mod.simpleserverutilities.network.DungeonEditorRequestPayload;
import be.winnetrie.mod.simpleserverutilities.network.DungeonLobbyDataPayload;
import be.winnetrie.mod.simpleserverutilities.network.DungeonLobbyRequestPayload;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.util.FormattedCharSequence;
import net.neoforged.neoforge.network.PacketDistributor;

/** Player-facing dungeon queue browser and active run status screen. */
public final class DungeonLobbyScreen extends Screen {
    private static final int W=720,H=468,LEFT=252,ROWS=12;
    private static final int PANEL=0xF0161D25,BORDER=0xFF586978,TEXT=0xFFF3F5F7,MUTED=0xFFAAB5BE,GOOD=0xFF83E39A,ERROR=0xFFFF8585,ACCENT=0xFF7FC8FF,WARN=0xFFFFD36A;
    private DungeonLobbyDataPayload data; private final Screen parent; private String selectedId=""; private long nextRequestId=1L; private boolean awaiting;

    public DungeonLobbyScreen(DungeonLobbyDataPayload data, Screen parent){super(Component.literal("Customized Dungeons"));this.data=data;this.parent=parent;nextRequestId=Math.max(1L,data.requestId()+1L);if(!data.queuedDungeonId().isBlank())selectedId=data.queuedDungeonId();else if(!data.dungeons().isEmpty())selectedId=data.dungeons().getFirst().id();}

    @Override protected void init(){int x=px(),y=py();List<DungeonLobbyDataPayload.DungeonEntry> values=data.dungeons();for(int i=0;i<Math.min(ROWS,values.size());i++){var dungeon=values.get(i);Button b=addRenderableWidget(Button.builder(Component.literal(trim(dungeon.displayName(),31)),ignored->{selectedId=dungeon.id();rebuildWidgets();}).bounds(x+16,y+52+i*27,LEFT-32,23).build());b.active=!dungeon.id().equals(selectedId);}addRenderableWidget(Button.builder(Component.literal("Refresh"),ignored->request("refresh","")).bounds(x+16,y+H-30,72,20).build());addRenderableWidget(Button.builder(Component.literal("Close"),ignored->onClose()).bounds(x+W-84,y+H-30,68,20).build());var selected=selected();if(selected!=null){int bx=x+LEFT+18,by=y+H-30;String label=selected.activeHere()?"Leave run":selected.queuedHere()?"Leave queue":"Join queue";Button primary=addRenderableWidget(Button.builder(Component.literal(label),ignored->{if(selected.queuedHere()||selected.activeHere())request("leave",selected.id());else request("join",selected.id());}).bounds(bx,by,96,20).build());primary.active=!awaiting&&(selected.queuedHere()||selected.activeHere()||selected.enabled()&&selected.requirementsMet());if(data.canAdmin()){addRenderableWidget(Button.builder(Component.literal("Edit"),ignored->edit(selected.id())).bounds(bx+102,by,52,20).build());addRenderableWidget(Button.builder(Component.literal("Force"),ignored->request("force_start",selected.id())).bounds(bx+160,by,70,20).build());Button complete=addRenderableWidget(Button.builder(Component.literal("Complete"),ignored->request("complete",selected.id())).bounds(bx+236,by,76,20).build());complete.active=selected.runningRuns()>0;Button fail=addRenderableWidget(Button.builder(Component.literal("Fail"),ignored->request("fail",selected.id())).bounds(bx+318,by,52,20).build());fail.active=selected.runningRuns()>0;addRenderableWidget(Button.builder(Component.literal("Delete"),ignored->request("delete",selected.id())).bounds(bx+376,by,60,20).build());Button advance=addRenderableWidget(Button.builder(Component.literal("Advance stage"),ignored->request("advance_stage",selected.id())).bounds(bx,by-24,112,20).build());advance.active=selected.activeHere();if(selected.blockedArenas()>0)addRenderableWidget(Button.builder(Component.literal("Release blocked arenas"),ignored->request("release_arena",selected.id())).bounds(bx+118,by-24,148,20).build());}}if(data.canAdmin())addRenderableWidget(Button.builder(Component.literal("Create dungeon"),ignored->edit("")).bounds(x+W-126,y+16,110,20).build());}

    private DungeonLobbyDataPayload.DungeonEntry selected(){for(var d:data.dungeons())if(d.id().equals(selectedId))return d;return data.dungeons().isEmpty()?null:data.dungeons().getFirst();}
    private void request(String action,String id){if(awaiting)return;awaiting=true;PacketDistributor.sendToServer(new DungeonLobbyRequestPayload(action,id,nextRequestId++));rebuildWidgets();}
    private void edit(String id){PacketDistributor.sendToServer(new DungeonEditorRequestPayload(id,nextRequestId++));}
    public void accept(DungeonLobbyDataPayload payload){if(payload==null)return;data=payload;awaiting=false;nextRequestId=Math.max(nextRequestId,payload.requestId()+1L);boolean present=false;for(var d:data.dungeons())if(d.id().equals(selectedId)){present=true;break;}if(!present)selectedId=data.dungeons().isEmpty()?"":data.dungeons().getFirst().id();rebuildWidgets();}
    public void refreshFromEditor(){request("refresh","");}
    @Override public void onClose(){if(minecraft!=null)minecraft.setScreen(parent);}

    @Override public void render(GuiGraphics g,int mouseX,int mouseY,float partialTick){int x=px(),y=py();SsuGuiScale.fullscreenDim(g, this, 0xA5000000);g.fill(x,y,x+W,y+H,PANEL);g.renderOutline(x,y,W,H,BORDER);g.drawString(font,"Dungeon Lobby",x+16,y+17,TEXT,true);String state=data.activeRunId().isBlank()?data.queuedDungeonId().isBlank()?"Not queued":"Queued: "+data.queuedDungeonId():"Active run: "+data.activeRunId();g.drawString(font,trim(state,70),x+126,y+18,MUTED,false);g.fill(x+LEFT,y+42,x+LEFT+1,y+H-40,BORDER);for(int i=0;i<Math.min(ROWS,data.dungeons().size());i++){var d=data.dungeons().get(i);int ry=y+52+i*27;int color=d.activeHere()?GOOD:d.queuedHere()?ACCENT:!d.enabled()||!d.requirementsMet()?MUTED:TEXT;String mark=d.activeHere()?"▶":d.queuedHere()?"◆":d.freeArenas()>0?"•":"○";g.drawString(font,mark,x+20,ry+7,color,true);g.drawString(font,d.queuedPlayers()+" queued",x+LEFT-78,ry+7,MUTED,false);}var d=selected();if(d==null)g.drawString(font,"No dungeons are configured.",x+LEFT+18,y+62,MUTED,false);else drawDungeon(g,d,x+LEFT+18,y+52);if(!data.notice().isBlank())g.drawString(font,trim(data.notice(),100),x+96,y+H-25,data.error()?ERROR:GOOD,false);else if(awaiting)g.drawString(font,"Processing dungeon action…",x+96,y+H-25,MUTED,false);super.render(g,mouseX,mouseY,partialTick);}

    private void drawDungeon(GuiGraphics g,DungeonLobbyDataPayload.DungeonEntry d,int x,int y){g.drawString(font,d.displayName(),x,y,TEXT,true);g.drawString(font,d.id()+" • "+d.stageCount()+" stage(s)",x,y+16,MUTED,false);List<FormattedCharSequence> lines=font.split(Component.literal(d.description()),W-LEFT-52);for(int i=0;i<Math.min(8,lines.size());i++)g.drawString(font,lines.get(i),x,y+40+i*11,TEXT,false);int sy=y+142;g.drawString(font,"Party queue",x,sy,ACCENT,true);g.drawString(font,d.queuedPlayers()+" waiting • starts at "+d.minPlayers()+" • maximum "+d.maxPlayers(),x,sy+17,TEXT,false);g.drawString(font,d.runningRuns()+" running run(s) • "+d.freeArenas()+" arena(s) free • "+d.blockedArenas()+" blocked",x,sy+32,d.freeArenas()>0?GOOD:WARN,false);g.drawString(font,d.livesPerPlayer()==0?"Unlimited lives":d.livesPerPlayer()+" lives per player",x,sy+47,TEXT,false);int ry=sy+78;g.drawString(font,"Requirements",x,ry,ACCENT,true);g.drawString(font,trim(d.requirementsMet()?"Available":d.requirementReason(),72),x,ry+17,d.requirementsMet()?GOOD:ERROR,false);if(d.activeHere()){int my=ry+52;g.drawString(font,"Your run",x,my,ACCENT,true);g.drawString(font,"State: "+d.runState().replace('_',' ')+" • Stage "+d.currentStage()+"/"+d.stageCount()+" • Lives "+(d.livesPerPlayer()==0?"∞":Integer.toString(d.remainingLives())),x,my+17,GOOD,false);g.drawString(font,trim(d.stageName()+" — "+d.stageProgress()+" / "+d.stageRequired(),74),x,my+32,TEXT,false);}}
    private int px(){return(width-W)/2;}private int py(){return(height-H)/2;}private static String trim(String value,int max){if(value==null)return"";return value.length()<=max?value:value.substring(0,Math.max(0,max-1))+"…";}@Override public boolean isPauseScreen(){return false;}
}
