package be.winnetrie.mod.simpleserverutilities.client.gui;

import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;import java.util.function.BiConsumer;
import net.minecraft.client.gui.GuiGraphicsExtractor;import net.minecraft.client.gui.components.Button;import net.minecraft.client.gui.components.EditBox;import net.minecraft.client.gui.screens.Screen;import net.minecraft.client.input.MouseButtonEvent;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.network.chat.Component;import net.minecraft.resources.Identifier;import net.minecraft.world.item.BlockItem;import net.minecraft.world.item.ItemStack;
/** Clear inventory-backed editor for jail task requirements and issued tools. Nothing is consumed from the admin. */
public final class JailTaskEditorScreen extends Screen{
 private static final int W=500,H=330,PANEL=0xF0161D25,BORDER=0xFF586978,TEXT=0xFFF3F5F7,MUTED=0xFFAAB5BE,GOOD=0xFF83E39A,SELECTED=0xFFFFC95A;private final Screen parent;private final BiConsumer<Map<String,Integer>,List<String>> saveCallback;private final Map<String,Integer> initialAmounts=new LinkedHashMap<>();private final String[] blocks=new String[9],tools=new String[9];private final EditBox[] amounts=new EditBox[9];private boolean selectingTools;private int selectedSlot;private String notice="";
 public JailTaskEditorScreen(Screen parent,Map<String,Integer> requirements,List<String> toolItems,BiConsumer<Map<String,Integer>,List<String>> saveCallback){super(Component.literal("Jail Task Setup"));this.parent=parent;this.saveCallback=saveCallback;if(requirements!=null)this.initialAmounts.putAll(requirements);int i=0;if(requirements!=null)for(var e:requirements.entrySet()){if(i>=9)break;blocks[i]=e.getKey();i++;}if(toolItems!=null)for(i=0;i<Math.min(9,toolItems.size());i++)tools[i]=toolItems.get(i);}
 @Override protected void init(){int x=left(),y=top();int i=0;for(i=0;i<9;i++){amounts[i]=new EditBox(font,x+24+i*50,y+80,42,18,Component.literal("Amount"));amounts[i].setMaxLength(7);amounts[i].setValue(Integer.toString(blocks[i]==null?64:initialAmounts.getOrDefault(blocks[i],64)));addRenderableWidget(amounts[i]);}addRenderableWidget(Button.builder(Component.literal("Edit required blocks"),b->{selectingTools=false;selectedSlot=0;}).bounds(x+16,y+112,132,18).build());addRenderableWidget(Button.builder(Component.literal("Edit issued tools"),b->{selectingTools=true;selectedSlot=0;}).bounds(x+156,y+112,112,18).build());addRenderableWidget(Button.builder(Component.literal("Back"),b->back()).bounds(x+16,y+H-26,64,18).build());addRenderableWidget(Button.builder(Component.literal("Save task"),b->save()).bounds(x+W-94,y+H-26,78,18).build());}
 @Override public boolean mouseClicked(MouseButtonEvent e,boolean dbl){int mx=(int)e.x(),my=(int)e.y(),button=e.buttonInfo().button();int req=slotAt(mx,my,left()+28,top()+52,50);if(req>=0){selectingTools=false;selectedSlot=req;if(button==1){blocks[req]=null;return true;}return true;}int tool=slotAt(mx,my,left()+28,top()+144,50);if(tool>=0){selectingTools=true;selectedSlot=tool;if(button==1){tools[tool]=null;return true;}return true;}if(button==0||button==1){int inv=inventorySlotAt(mx,my);if(inv>=0){ItemStack stack=inventory(inv);if(stack.isEmpty()){notice="That inventory slot is empty.";return true;}Identifier id=BuiltInRegistries.ITEM.getKey(stack.getItem());if(id==null){notice="That item has no registry ID.";return true;}if(selectingTools){tools[selectedSlot]=id.toString();notice="Issued tool slot "+(selectedSlot+1)+" set to "+stack.getHoverName().getString()+".";}else{if(!(stack.getItem() instanceof BlockItem blockItem)){notice="Required-work slots accept block items only.";return true;}Identifier blockId=BuiltInRegistries.BLOCK.getKey(blockItem.getBlock());if(blockId==null){notice="That block has no registry ID.";return true;}blocks[selectedSlot]=blockId.toString();notice="Required block "+(selectedSlot+1)+" set to "+stack.getHoverName().getString()+".";}return true;}}return super.mouseClicked(e,dbl);}
 private void save(){LinkedHashMap<String,Integer> requirements=new LinkedHashMap<>();ArrayList<String> toolList=new ArrayList<>();for(int i=0;i<9;i++){if(blocks[i]!=null&&!blocks[i].isBlank()){int amount=intValue(amounts[i],64);if(amount>0)requirements.merge(blocks[i],amount,Integer::sum);}if(tools[i]!=null&&!tools[i].isBlank())toolList.add(tools[i]);}if(requirements.isEmpty()){notice="Task punishment needs at least one required block.";return;}saveCallback.accept(requirements,List.copyOf(toolList));back();}
 private void back(){if(minecraft!=null)minecraft.setScreenAndShow(parent);}
 @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float pt){int x=left(),y=top();g.fill(0,0,width,height,0xA5000000);g.fill(x,y,x+W,y+H,PANEL);g.outline(x,y,W,H,BORDER);g.text(font,"Task punishment setup",x+16,y+14,TEXT,true);g.text(font,"Required blocks — click a slot, then click a block in your inventory. Right-click to clear.",x+16,y+32,MUTED,false);for(int i=0;i<9;i++)drawGhost(g,blocks[i],x+28+i*50,y+52,i==selectedSlot&&!selectingTools,mx,my);g.text(font,"Issued tools — copied as jail-only tools; your admin inventory is never consumed.",x+16,y+134,MUTED,false);for(int i=0;i<9;i++)drawGhost(g,tools[i],x+28+i*50,y+144,i==selectedSlot&&selectingTools,mx,my);g.text(font,"Inventory",x+167,y+176,MUTED,false);renderInventory(g,x+167,y+191,mx,my);if(!notice.isBlank())g.text(font,trim(notice,70),x+16,y+H-44,GOOD,false);super.extractRenderState(g,mx,my,pt);}
 private void drawGhost(GuiGraphicsExtractor g,String id,int x,int y,boolean selected,int mx,int my){boolean hover=SsuGuiGeometry.inside(mx,my,x,y,20,20);g.fill(x,y,x+20,y+20,0xFF090D12);g.outline(x,y,20,20,selected?SELECTED:(hover?GOOD:BORDER));ItemStack stack=stack(id);if(!stack.isEmpty()){g.item(stack,x+2,y+2);if(hover)g.setTooltipForNextFrame(font,stack,mx,my);}}
 private void renderInventory(GuiGraphicsExtractor g,int sx,int sy,int mx,int my){for(int row=0;row<3;row++)for(int col=0;col<9;col++)drawInventory(g,9+row*9+col,sx+col*18,sy+row*18,mx,my);for(int col=0;col<9;col++)drawInventory(g,col,sx+col*18,sy+60,mx,my);}private void drawInventory(GuiGraphicsExtractor g,int slot,int x,int y,int mx,int my){boolean h=SsuGuiGeometry.inside(mx,my,x,y,18,18);g.fill(x,y,x+18,y+18,h?0xFF28323C:0xD00B1015);g.outline(x,y,18,18,h?GOOD:BORDER);ItemStack s=inventory(slot);if(!s.isEmpty()){g.item(s,x+1,y+1);g.itemDecorations(font,s,x+1,y+1);if(h)g.setTooltipForNextFrame(font,s,mx,my);}}
 private int slotAt(int mx,int my,int x,int y,int gap){for(int i=0;i<9;i++)if(SsuGuiGeometry.inside(mx,my,x+i*gap,y,20,20))return i;return-1;}private int inventorySlotAt(int mx,int my){int x=left()+167,y=top()+191;for(int row=0;row<3;row++)for(int col=0;col<9;col++)if(SsuGuiGeometry.inside(mx,my,x+col*18,y+row*18,18,18))return 9+row*9+col;for(int col=0;col<9;col++)if(SsuGuiGeometry.inside(mx,my,x+col*18,y+60,18,18))return col;return-1;}private ItemStack inventory(int slot){if(minecraft==null||minecraft.player==null||slot<0||slot>=36)return ItemStack.EMPTY;ItemStack s=minecraft.player.getInventory().getItem(slot);return s==null?ItemStack.EMPTY:s;}private static ItemStack stack(String id){if(id==null||id.isBlank())return ItemStack.EMPTY;try{return BuiltInRegistries.ITEM.getOptional(Identifier.parse(id)).map(ItemStack::new).orElse(ItemStack.EMPTY);}catch(Exception e){return ItemStack.EMPTY;}}private static int intValue(EditBox e,int f){try{return Math.max(1,Math.min(1_000_000,Integer.parseInt(e.getValue().trim())));}catch(Exception ex){return f;}}private static String trim(String s,int max){return s==null?"":s.length()<=max?s:s.substring(0,max-1)+"…";}private int left(){return(width-W)/2;}private int top(){return(height-H)/2;}@Override public void onClose(){back();}@Override public boolean isPauseScreen(){return false;}
}
