package be.winnetrie.mod.simpleserverutilities.client.gui;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import be.winnetrie.mod.simpleserverutilities.hologram.HologramRichText;
import be.winnetrie.mod.simpleserverutilities.network.JailAdminActionPayload;
import be.winnetrie.mod.simpleserverutilities.network.JailAdminDataPayload;
import be.winnetrie.mod.simpleserverutilities.network.JailAdminRequestPayload;
import be.winnetrie.mod.simpleserverutilities.network.PlayerManagementRequestPayload;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.network.PacketDistributor;

/** Scan-friendly administrator overview of all active prisoners. */
public final class JailPrisonerOverviewScreen extends Screen {
    private static final Gson GSON=new Gson(); private static final int W=650,H=360,PANEL=0xF0161D25,BORDER=0xFF586978,TEXT=0xFFF3F5F7,MUTED=0xFFAAB5BE,GOOD=0xFF83E39A,WARNING=0xFFFFB86B;
    private JailAdminDataPayload data; private final Screen parent; private final List<JsonObject> prisoners=new ArrayList<>(); private int selected,page; private int onlineFilter; private int pathFilter; private long request=1000L;
    public JailPrisonerOverviewScreen(JailAdminDataPayload data,Screen parent){super(Component.literal("Jail Prisoners"));this.data=data;this.parent=parent;parse();}
    public void accept(JailAdminDataPayload next){data=next;parse();rebuildWidgets();}
    private void parse(){prisoners.clear();try{JsonObject root=GSON.fromJson(data.json(),JsonObject.class);JsonArray arr=root!=null&&root.has("prisoners")?root.getAsJsonArray("prisoners"):new JsonArray();for(var e:arr)if(e.isJsonObject())prisoners.add(e.getAsJsonObject());}catch(Exception ignored){}prisoners.sort(Comparator.comparing(o->str(o,"name"),String.CASE_INSENSITIVE_ORDER));selected=Math.max(0,Math.min(selected,Math.max(0,filtered().size()-1)));}
    private List<JsonObject> filtered(){return prisoners.stream().filter(p->onlineFilter==0||(onlineFilter==1&&bool(p,"online"))||(onlineFilter==2&&!bool(p,"online"))).filter(p->pathFilter==0||(pathFilter==1&&"TASK".equals(str(p,"selectedPath")))||(pathFilter==2&&"TIME".equals(str(p,"selectedPath")))||(pathFilter==3&&"PENDING".equals(str(p,"selectedPath")))).toList();}
    @Override protected void init(){int x=left(),y=top();List<JsonObject> list=filtered();int rows=10,start=page*rows;for(int i=0;i<rows&&start+i<list.size();i++){int row=start+i;JsonObject p=list.get(row);String label=(bool(p,"online")?"● ":"○ ")+str(p,"name")+" • "+pathLabel(str(p,"selectedPath"));Button b=addRenderableWidget(Button.builder(Component.literal(trim(label,25)),v->{selected=row;rebuildWidgets();}).bounds(x+16,y+60+i*23,218,18).build());b.active=row!=selected;}
        int maxPage=Math.max(0,(list.size()-1)/rows);page=Math.min(page,maxPage);Button prev=addRenderableWidget(Button.builder(Component.literal("‹"),v->{page=Math.max(0,page-1);selected=page*rows;rebuildWidgets();}).bounds(x+16,y+H-54,28,18).build());prev.active=page>0;Button next=addRenderableWidget(Button.builder(Component.literal("›"),v->{page=Math.min(maxPage,page+1);selected=page*rows;rebuildWidgets();}).bounds(x+206,y+H-54,28,18).build());next.active=page<maxPage;
        addRenderableWidget(Button.builder(Component.literal("Online: "+onlineLabel()),v->{onlineFilter=(onlineFilter+1)%3;page=0;selected=0;rebuildWidgets();}).bounds(x+250,y+34,100,18).build());addRenderableWidget(Button.builder(Component.literal("Path: "+pathFilterLabel()),v->{pathFilter=(pathFilter+1)%4;page=0;selected=0;rebuildWidgets();}).bounds(x+358,y+34,104,18).build());addRenderableWidget(Button.builder(Component.literal("Refresh"),v->PacketDistributor.sendToServer(new JailAdminRequestPayload("",request++))).bounds(x+470,y+34,68,18).build());
        if(!list.isEmpty()){JsonObject p=list.get(selected);String uuid=str(p,"uuid");Button tp=addRenderableWidget(Button.builder(Component.literal("Teleport to prisoner"),v->PacketDistributor.sendToServer(new JailAdminActionPayload("prisoner_tp",uuid,"{}",request++))).bounds(x+250,y+H-54,126,18).build());tp.active=bool(p,"online");addRenderableWidget(Button.builder(Component.literal("Open punishment"),v->PacketDistributor.sendToServer(new PlayerManagementRequestPayload(uuid,request++))).bounds(x+384,y+H-54,112,18).build());addRenderableWidget(Button.builder(Component.literal("Release"),v->PacketDistributor.sendToServer(new JailAdminActionPayload("prisoner_release",uuid,"{}",request++))).bounds(x+504,y+H-54,70,18).build());}
        addRenderableWidget(Button.builder(Component.literal("Back"),v->onClose()).bounds(x+16,y+H-28,64,18).build());}
    @Override public void render(GuiGraphics g,int mx,int my,float pt){int x=left(),y=top();SsuGuiScale.fullscreenDim(g, this, 0xA5000000);g.fill(x,y,x+W,y+H,PANEL);g.renderOutline(x,y,W,H,BORDER);g.drawString(font,"Active Jail Prisoners",x+16,y+14,TEXT,true);g.drawString(font,prisoners.size()+" active prisoner(s)",x+250,y+16,MUTED,false);List<JsonObject> list=filtered();if(list.isEmpty()){g.drawString(font,"No prisoners match the current filters.",x+250,y+74,MUTED,false);}else{JsonObject p=list.get(Math.max(0,Math.min(selected,list.size()-1)));int dx=x+250;g.drawString(font,str(p,"name")+(bool(p,"online")?"  • ONLINE":"  • OFFLINE"),dx,y+70,bool(p,"online")?GOOD:MUTED,true);g.drawString(font,"Jail: "+str(p,"jailName")+"  •  Path: "+pathLabel(str(p,"selectedPath")),dx,y+94,TEXT,false);g.drawString(font,"Started: "+date(num(p,"startedAt"))+"  •  Remaining: "+duration(num(p,"secondsRemaining")),dx,y+116,MUTED,false);if("TASK".equals(str(p,"selectedPath")))g.drawString(font,"Task progress: "+num(p,"taskDone")+" / "+num(p,"taskRequired")+"  ("+String.format(Locale.ROOT,"%.1f",decimal(p,"taskPercent"))+"%)",dx,y+138,GOOD,false);if("TIME".equals(str(p,"selectedPath")))g.drawString(font,"Solitude cell: "+(num(p,"assignedCell")+1),dx,y+138,MUTED,false);if("PENDING".equals(str(p,"selectedPath")))g.drawString(font,"Choice still open — automatically selects Task when timer reaches zero.",dx,y+138,WARNING,false);String buyout=num(p,"buyoutMinor")<=0?"not offered":("PENDING".equals(str(p,"selectedPath"))?"available ("+str(p,"buyoutFormatted")+")":"locked ("+str(p,"buyoutFormatted")+")");g.drawString(font,"Mode: "+str(p,"sentenceMode")+"  •  Buyout: "+trim(buyout,42),dx,y+158,MUTED,false);g.drawString(font,"Reason",dx,y+184,MUTED,false);drawWrapped(g,HologramRichText.stripFormatting(str(p,"reason")),dx,y+200,W-280,TEXT,4);}if(!data.notice().isBlank())g.drawString(font,trim(data.notice(),80),x+90,y+H-24,data.error()?0xFFFF8585:GOOD,false);super.render(g,mx,my,pt);}
    private void drawWrapped(GuiGraphics g,String text,int x,int y,int w,int color,int max){var lines=font.split(Component.literal(text),w);for(int i=0;i<Math.min(max,lines.size());i++)g.drawString(font,lines.get(i),x,y+i*11,color,false);}
    @Override public void onClose(){if(minecraft!=null){minecraft.setScreen(parent);if(parent instanceof JailAdministrationScreen admin)PacketDistributor.sendToServer(new JailAdminRequestPayload(admin.data().selectedId(),request++));}} @Override public boolean isPauseScreen(){return false;}private int left(){return(width-W)/2;}private int top(){return(height-H)/2;}
    private String onlineLabel(){return switch(onlineFilter){case 1->"ONLINE";case 2->"OFFLINE";default->"ALL";};}private String pathFilterLabel(){return switch(pathFilter){case 1->"TASK";case 2->"TIME";case 3->"CHOICE";default->"ALL";};}private static String pathLabel(String s){return switch(s){case"TASK"->"Task";case"TIME"->"Solitude";case"PENDING"->"Choice";default->s;};}private static String str(JsonObject o,String k){try{return o.has(k)?o.get(k).getAsString():"";}catch(Exception e){return"";}}private static boolean bool(JsonObject o,String k){try{return o.has(k)&&o.get(k).getAsBoolean();}catch(Exception e){return false;}}private static long num(JsonObject o,String k){try{return o.has(k)?o.get(k).getAsLong():0L;}catch(Exception e){return 0L;}}private static double decimal(JsonObject o,String k){try{return o.has(k)?o.get(k).getAsDouble():0D;}catch(Exception e){return 0D;}}private static String date(long ms){if(ms<=0)return"-";return java.time.Instant.ofEpochMilli(ms).atZone(java.time.ZoneId.systemDefault()).format(java.time.format.DateTimeFormatter.ofPattern("dd/MM HH:mm"));}private static String duration(long sec){long d=sec/86400,h=(sec%86400)/3600,m=(sec%3600)/60;if(d>0)return d+"d "+h+"h";if(h>0)return h+"h "+m+"m";return Math.max(0,m)+"m";}private static String trim(String v,int m){if(v==null)return"";return v.length()<=m?v:v.substring(0,Math.max(0,m-1))+"…";}
}
