package be.winnetrie.mod.simpleserverutilities.client.gui;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import be.winnetrie.mod.simpleserverutilities.network.NpcAbilityEditorOpenPayload;
import be.winnetrie.mod.simpleserverutilities.network.NpcAbilityEditorResultPayload;
import be.winnetrie.mod.simpleserverutilities.network.NpcAbilityEditorSubmitPayload;
import be.winnetrie.mod.simpleserverutilities.npc.NpcAbilityDefinition;
import be.winnetrie.mod.simpleserverutilities.npc.NpcAbilityPreset;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.client.network.ClientPacketDistributor;

/** Standalone editor for one reusable server-wide NPC ability. */
public final class NpcAbilityWorkshopScreen extends Screen {
    private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();
    private static final int W=680,H=410,PANEL=0xF0161D25,BORDER=0xFF586978,TEXT=0xFFF3F5F7,MUTED=0xFFAAB5BE,ERROR=0xFFFF8585,GOOD=0xFF7DFF9B;
    private final Screen parent; private final String originalAbilityId; private final int usageCount; private NpcAbilityDefinition ability;
    private Page page=Page.CORE; private NpcAbilityPreset preset=NpcAbilityPreset.CUSTOM; private String notice="";private boolean noticeError;private long nextRequestId=1L;
    private EditBox id,name,cooldown,windup,recovery,minRange,maxRange,chance,damage,heal;
    private EditBox radius,coneAngle,knockback,stun,slow,slowAmp,debuffEffect,debuffDuration,debuffAmp,bleedDamage,bleedDuration,bleedInterval;
    private EditBox dotDamage,dotDuration,dotInterval,hotAmount,hotDuration,hotInterval,hitCount,pulseInterval,chargeSpeed,minTargets;

    public NpcAbilityWorkshopScreen(NpcAbilityEditorOpenPayload payload,Screen parent){super(Component.literal("NPC Ability Workshop"));this.parent=parent;this.originalAbilityId=payload.originalAbilityId();this.usageCount=payload.usageCount();try{ability=GSON.fromJson(payload.definitionJson(),NpcAbilityDefinition.class);}catch(RuntimeException e){ability=null;}if(ability==null)ability=new NpcAbilityDefinition();ability.normalize();}
    public void acceptResult(NpcAbilityEditorResultPayload result){notice=result.message();noticeError=!result.success();if(result.success()){if(parent instanceof NpcAbilityLibraryScreen library)library.refreshFromEditor(result.message());if(minecraft!=null)minecraft.setScreenAndShow(parent);}else rebuildWidgets();}

    @Override protected void init(){clearWidgets();int x=left(),y=top();
        addRenderableWidget(Button.builder(Component.literal("Preset: "+preset.label()),b->{saveFields();preset=preset.next();rebuildWidgets();}).bounds(x+14,y+42,210,20).build());
        addRenderableWidget(Button.builder(Component.literal("Apply preset"),b->applyPreset()).bounds(x+232,y+42,110,20).build());
        addRenderableWidget(Button.builder(Component.literal("Save"),b->submit()).bounds(x+W-150,y+42,64,20).build());
        addRenderableWidget(Button.builder(Component.literal("Cancel"),b->onClose()).bounds(x+W-78,y+42,64,20).build());
        addRenderableWidget(Button.builder(Component.literal("Core"),b->switchPage(Page.CORE)).bounds(x+14,y+76,150,20).build());
        addRenderableWidget(Button.builder(Component.literal("Effects / AoE"),b->switchPage(Page.EFFECTS)).bounds(x+172,y+76,150,20).build());
        addRenderableWidget(Button.builder(Component.literal("Timing / AI"),b->switchPage(Page.CHANNEL)).bounds(x+330,y+76,150,20).build());
        if(page==Page.CORE)initCore(x,y);else if(page==Page.EFFECTS)initEffects(x,y);else initChannel(x,y);
    }
    private void initCore(int x,int y){NpcAbilityDefinition a=ability;
        id=field(x+14,y+122,150,48,a.id);id.active=originalAbilityId.isBlank();name=field(x+172,y+122,190,64,a.displayName);
        toggle(x+370,y+122,100,"Enabled",a.enabled,()->a.enabled=!a.enabled);toggle(x+478,y+122,188,"Equipment damage",a.damageUsesEquipment,()->a.damageUsesEquipment=!a.damageUsesEquipment);
        addRenderableWidget(Button.builder(Component.literal("Executor: "+a.abilityType().label()),b->{saveFields();a.type=a.abilityType().next().id();rebuildWidgets();}).bounds(x+14,y+164,210,20).build());
        addRenderableWidget(Button.builder(Component.literal("Channel: "+a.attackKind().label()),b->{saveFields();a.attackKind=a.attackKind().next().id();rebuildWidgets();}).bounds(x+232,y+164,170,20).build());
        addRenderableWidget(Button.builder(Component.literal("Damage type: "+a.damageSchool().label()),b->{saveFields();a.damageSchool=a.damageSchool().next().id();rebuildWidgets();}).bounds(x+410,y+164,256,20).build());
        damage=field(x+14,y+222,92,16,number(a.damage));heal=field(x+114,y+222,92,16,number(a.healAmount));minRange=field(x+214,y+222,92,16,number(a.minRange));maxRange=field(x+314,y+222,92,16,number(a.maxRange));chance=field(x+414,y+222,92,16,number(a.chance));cooldown=field(x+514,y+222,152,16,Integer.toString(a.cooldownTicks));
        addRenderableWidget(Button.builder(Component.literal("Shape: "+a.abilityShape().label()),b->{saveFields();a.shape=a.abilityShape().next().id();rebuildWidgets();}).bounds(x+14,y+272,220,20).build());
        minTargets=field(x+242,y+272,110,3,Integer.toString(a.minTargets));
    }
    private void initEffects(int x,int y){NpcAbilityDefinition a=ability;
        addRenderableWidget(Button.builder(Component.literal("Shape: "+a.abilityShape().label()),b->{saveFields();a.shape=a.abilityShape().next().id();rebuildWidgets();}).bounds(x+14,y+116,210,20).build());
        radius=field(x+232,y+116,90,12,number(a.radius));coneAngle=field(x+330,y+116,90,12,number(a.coneAngleDegrees));knockback=field(x+428,y+116,90,12,number(a.knockback));stun=field(x+526,y+116,140,8,Integer.toString(a.stunTicks));
        slow=field(x+14,y+174,95,8,Integer.toString(a.slowTicks));slowAmp=field(x+117,y+174,95,4,Integer.toString(a.slowAmplifier));bleedDamage=field(x+220,y+174,95,12,number(a.bleedDamage));bleedDuration=field(x+323,y+174,95,8,Integer.toString(a.bleedDurationTicks));bleedInterval=field(x+426,y+174,95,8,Integer.toString(a.bleedIntervalTicks));
        dotDamage=field(x+14,y+232,95,12,number(a.dotDamage));dotDuration=field(x+117,y+232,95,8,Integer.toString(a.dotDurationTicks));dotInterval=field(x+220,y+232,95,8,Integer.toString(a.dotIntervalTicks));hotAmount=field(x+323,y+232,95,12,number(a.hotAmount));hotDuration=field(x+426,y+232,95,8,Integer.toString(a.hotDurationTicks));hotInterval=field(x+529,y+232,137,8,Integer.toString(a.hotIntervalTicks));
        debuffEffect=field(x+14,y+290,310,128,a.debuffEffect);debuffDuration=field(x+332,y+290,145,8,Integer.toString(a.debuffDurationTicks));debuffAmp=field(x+485,y+290,181,4,Integer.toString(a.debuffAmplifier));
    }
    private void initChannel(int x,int y){NpcAbilityDefinition a=ability;
        hitCount=field(x+14,y+122,105,4,Integer.toString(a.hitCount));pulseInterval=field(x+127,y+122,115,6,Integer.toString(a.pulseIntervalTicks));windup=field(x+250,y+122,105,6,Integer.toString(a.windupTicks));recovery=field(x+363,y+122,105,6,Integer.toString(a.recoveryTicks));chargeSpeed=field(x+476,y+122,190,12,number(a.chargeSpeed));
        toggle(x+14,y+178,145,"Channeling",a.channeling,()->a.channeling=!a.channeling);toggle(x+167,y+178,190,"Interrupt on damage",a.interruptOnDamage,()->a.interruptOnDamage=!a.interruptOnDamage);toggle(x+365,y+178,175,"Interrupt on move",a.interruptOnMove,()->a.interruptOnMove=!a.interruptOnMove);toggle(x+14,y+214,210,"Requires stationary",a.requiresStationary,()->a.requiresStationary=!a.requiresStationary);
    }
    private void applyPreset(){saveFields();NpcAbilityDefinition replacement=preset.create(1);replacement.id=ability.id;replacement.displayName=ability.displayName;ability=replacement.normalize();notice="Applied "+preset.label()+" preset.";noticeError=false;rebuildWidgets();}
    private void switchPage(Page next){saveFields();page=next;rebuildWidgets();}
    private void submit(){if(!saveFields())return;String json=GSON.toJson(ability);if(json.length()>NpcAbilityEditorOpenPayload.MAX_JSON){notice="Ability is too large for the editor payload.";noticeError=true;return;}ClientPacketDistributor.sendToServer(new NpcAbilityEditorSubmitPayload(originalAbilityId,json,nextRequestId++));notice="Saving…";noticeError=false;}
    private boolean saveFields(){try{NpcAbilityDefinition a=ability;if(id!=null)a.id=id.getValue();if(name!=null)a.displayName=name.getValue();if(cooldown!=null)a.cooldownTicks=integer(cooldown,4,72000,"cooldown");if(windup!=null)a.windupTicks=integer(windup,0,400,"wind-up");if(recovery!=null)a.recoveryTicks=integer(recovery,0,400,"recovery");if(minRange!=null)a.minRange=decimal(minRange,0,64,"min range");if(maxRange!=null)a.maxRange=decimal(maxRange,0,128,"max range");if(chance!=null)a.chance=decimal(chance,0,1,"chance");if(damage!=null)a.damage=decimal(damage,0,2048,"damage");if(heal!=null)a.healAmount=decimal(heal,0,2048,"healing");if(minTargets!=null)a.minTargets=integer(minTargets,0,64,"minimum targets");if(radius!=null)a.radius=decimal(radius,.25,32,"radius");if(coneAngle!=null)a.coneAngleDegrees=decimal(coneAngle,5,180,"cone angle");if(knockback!=null)a.knockback=decimal(knockback,0,8,"knockback");if(stun!=null)a.stunTicks=integer(stun,0,1200,"stun ticks");if(slow!=null)a.slowTicks=integer(slow,0,7200,"slow ticks");if(slowAmp!=null)a.slowAmplifier=integer(slowAmp,0,10,"slow amplifier");if(debuffEffect!=null)a.debuffEffect=debuffEffect.getValue();if(debuffDuration!=null)a.debuffDurationTicks=integer(debuffDuration,0,72000,"effect duration");if(debuffAmp!=null)a.debuffAmplifier=integer(debuffAmp,0,10,"effect amp");if(bleedDamage!=null)a.bleedDamage=decimal(bleedDamage,0,2048,"bleed damage");if(bleedDuration!=null)a.bleedDurationTicks=integer(bleedDuration,0,72000,"bleed duration");if(bleedInterval!=null)a.bleedIntervalTicks=integer(bleedInterval,1,1200,"bleed interval");if(dotDamage!=null)a.dotDamage=decimal(dotDamage,0,2048,"DoT damage");if(dotDuration!=null)a.dotDurationTicks=integer(dotDuration,0,72000,"DoT duration");if(dotInterval!=null)a.dotIntervalTicks=integer(dotInterval,1,1200,"DoT interval");if(hotAmount!=null)a.hotAmount=decimal(hotAmount,0,2048,"HoT amount");if(hotDuration!=null)a.hotDurationTicks=integer(hotDuration,0,72000,"HoT duration");if(hotInterval!=null)a.hotIntervalTicks=integer(hotInterval,1,1200,"HoT interval");if(hitCount!=null)a.hitCount=integer(hitCount,1,32,"hits/projectiles");if(pulseInterval!=null)a.pulseIntervalTicks=integer(pulseInterval,1,200,"pulse interval");if(chargeSpeed!=null)a.chargeSpeed=decimal(chargeSpeed,.2,8,"charge speed");a.phaseId="";a.normalize();notice="";return true;}catch(IllegalArgumentException e){notice=e.getMessage();noticeError=true;return false;}}

    @Override public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float pt){int x=left(),y=top();SsuGuiScale.fullscreenDim(g,this,0xA5000000);g.fill(x,y,x+W,y+H,PANEL);g.outline(x,y,W,H,BORDER);g.text(font,"NPC Ability Workshop",x+14,y+14,TEXT,true);g.text(font,ability.displayName+"  · used by "+usageCount+" NPC template(s)",x+228,y+18,MUTED,false);if(page==Page.CORE){label(g,"ID",x+14,y+111);label(g,"Name",x+172,y+111);label(g,"Damage / equip ×",x+14,y+211);label(g,"Healing",x+114,y+211);label(g,"Min range",x+214,y+211);label(g,"Max range",x+314,y+211);label(g,"Chance",x+414,y+211);label(g,"Cooldown ticks",x+514,y+211);label(g,"Min targets",x+242,y+261);g.text(font,"Min targets is evaluated inside the chosen shape. Thunderclap will not fire until enemies are actually inside its radius.",x+14,y+318,MUTED,false);}else if(page==Page.EFFECTS){label(g,"Radius",x+232,y+105);label(g,"Cone angle",x+330,y+105);label(g,"Knockback",x+428,y+105);label(g,"Stun ticks",x+526,y+105);label(g,"Slow ticks",x+14,y+163);label(g,"Slow amp",x+117,y+163);label(g,"Bleed dmg",x+220,y+163);label(g,"Bleed duration",x+323,y+163);label(g,"Bleed interval",x+426,y+163);label(g,"DoT dmg",x+14,y+221);label(g,"DoT duration",x+117,y+221);label(g,"DoT interval",x+220,y+221);label(g,"HoT amount",x+323,y+221);label(g,"HoT duration",x+426,y+221);label(g,"HoT interval",x+529,y+221);label(g,"Extra effect ID",x+14,y+279);label(g,"Effect duration",x+332,y+279);label(g,"Effect amp",x+485,y+279);}else{label(g,"Hits / projectiles",x+14,y+111);label(g,"Pulse interval",x+127,y+111);label(g,"Wind-up",x+250,y+111);label(g,"Recovery",x+363,y+111);label(g,"Charge speed",x+476,y+111);g.text(font,"Requires stationary makes the AI stop its existing path before casting and hold position while the ability owns movement.",x+14,y+264,MUTED,false);g.text(font,"Interrupt on move then reacts to real displacement/knockback instead of the NPC interrupting its own old path.",x+14,y+280,MUTED,false);}if(!notice.isBlank())g.text(font,notice,x+14,y+H-20,noticeError?ERROR:GOOD,false);super.extractRenderState(g,mx,my,pt);}
    private void toggle(int x,int y,int w,String text,boolean value,Runnable action){addRenderableWidget(Button.builder(Component.literal(text+": "+(value?"ON":"OFF")),b->{saveFields();action.run();rebuildWidgets();}).bounds(x,y,w,20).build());}
    private EditBox field(int x,int y,int w,int max,String value){EditBox e=new EditBox(font,x,y,w,20,Component.empty());e.setMaxLength(max);e.setValue(value);return addRenderableWidget(e);}private void label(GuiGraphicsExtractor g,String text,int x,int y){g.text(font,text,x,y,MUTED,false);}private int left(){return(width-W)/2;}private int top(){return(height-H)/2;}
    private static int integer(EditBox b,int min,int max,String label){try{int v=Integer.parseInt(b.getValue().trim());if(v<min||v>max)throw new Exception();return v;}catch(Exception e){throw new IllegalArgumentException(label+" must be "+min+"-"+max+".");}}private static double decimal(EditBox b,double min,double max,String label){try{double v=Double.parseDouble(b.getValue().trim().replace(',','.'));if(!Double.isFinite(v)||v<min||v>max)throw new Exception();return v;}catch(Exception e){throw new IllegalArgumentException(label+" must be "+min+"-"+max+".");}}private static String number(double v){return Math.rint(v)==v?Long.toString(Math.round(v)):Double.toString(v);}
    @Override public void onClose(){if(minecraft!=null)minecraft.setScreenAndShow(parent);}@Override public boolean isPauseScreen(){return false;}private enum Page{CORE,EFFECTS,CHANNEL}
}
