package be.winnetrie.mod.simpleserverutilities.economy;

public enum EconomyTransactionType {
    TRANSFER,
    ADMIN_GIVE,
    ADMIN_TAKE,
    ADMIN_SET,
    STARTING_BALANCE,
    RECOVERY,

    REGION_RENT,
    REGION_RENEW,
    REGION_OWNER_PAYOUT,
    REGION_OWNER_PAYOUT_REVERSAL,
    REGION_TREASURY_INCOME,
    REGION_TREASURY_INCOME_REVERSAL,
    REGION_REFUND,
    REGION_PAYMENT_ROLLBACK,

    TREASURY_ADMIN_DEPOSIT,
    TREASURY_ADMIN_WITHDRAW,
    TREASURY_PAYMENT,

    MAIL_ESCROW_DEPOSIT,
    MAIL_ESCROW_CLAIM,
    MAIL_ESCROW_REFUND,

    AUCTION_PURCHASE,
    AUCTION_SELLER_PAYOUT,
    AUCTION_PURCHASE_ROLLBACK
}
