package be.winnetrie.mod.simpleserverutilities.economy;

public enum EconomyTransactionType {
    TRANSFER,
    ADMIN_GIVE,
    ADMIN_TAKE,
    ADMIN_SET,
    STARTING_BALANCE,
    RECOVERY,

    CLAIM_TAX,
    WARP_RENT,
    WARP_RENEW,

    REGION_RENT,
    REGION_RENEW,
    REGION_OWNER_PAYOUT,
    REGION_OWNER_PAYOUT_REVERSAL,
    REGION_TREASURY_INCOME,
    REGION_TREASURY_INCOME_REVERSAL,
    REGION_REFUND,
    REGION_PAYMENT_ROLLBACK,

    TREASURY_ADMIN_DEPOSIT,
    TREASURY_ADMIN_WITHDRAW,
    TREASURY_PAYMENT,

    MAIL_ESCROW_DEPOSIT,
    MAIL_ESCROW_CLAIM,
    MAIL_ESCROW_REFUND,

    KIT_PURCHASE,
    JAIL_BUYOUT,

    AUCTION_PURCHASE,
    AUCTION_SELLER_PAYOUT,
    AUCTION_PURCHASE_ROLLBACK,

    NPC_SHOP_BUY,
    NPC_SHOP_BUY_ROLLBACK,
    NPC_SHOP_SELL,
    NPC_SHOP_SELL_ROLLBACK,
    NPC_SHOP_BUYBACK,
    NPC_SHOP_BUYBACK_ROLLBACK
}
