package be.winnetrie.mod.simpleserverutilities.kits;

import java.io.IOException;import java.nio.file.Files;import java.nio.file.Path;import java.util.ArrayList;import java.util.Comparator;import java.util.HashMap;import java.util.List;import java.util.Map;import java.util.UUID;
import com.google.gson.Gson;import com.google.gson.GsonBuilder;import com.google.gson.JsonElement;import com.google.gson.JsonNull;
import be.winnetrie.mod.simpleserverutilities.SimpleServerUtilities;import be.winnetrie.mod.simpleserverutilities.core.storage.DirtyJsonRecordStore;import be.winnetrie.mod.simpleserverutilities.economy.EconomyResult;import be.winnetrie.mod.simpleserverutilities.economy.EconomyTransactionType;import be.winnetrie.mod.simpleserverutilities.npc.NpcItemCodec;import be.winnetrie.mod.simpleserverutilities.permission.PermissionService;import be.winnetrie.mod.simpleserverutilities.storage.JsonStorage;import be.winnetrie.mod.simpleserverutilities.storage.StoragePaths;
import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.item.ItemStack;

/** Persistent kit catalogue and one-time/cooldown claim ledger. */
public final class KitManager{
 private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();private final DirtyJsonRecordStore definitionsStore=new DirtyJsonRecordStore();private final DirtyJsonRecordStore playersStore=new DirtyJsonRecordStore();private final Map<String,KitDefinition> definitions=new HashMap<>();private final Map<UUID,KitPlayerData> players=new HashMap<>();private Path definitionFolder,playerFolder;private MinecraftServer server;
 public synchronized void load(MinecraftServer server){this.server=server;definitionFolder=StoragePaths.kitDefinitions(StoragePaths.root(server));playerFolder=StoragePaths.kitPlayers(StoragePaths.root(server));definitionsStore.reset();playersStore.reset();definitions.clear();players.clear();try{Files.createDirectories(definitionFolder);Files.createDirectories(playerFolder);definitionsStore.discover(definitionFolder);playersStore.discover(playerFolder);for(Path file:JsonStorage.listJsonFiles(definitionFolder)){try{KitDefinition d=JsonStorage.read(GSON,file,KitDefinition.class);if(d!=null){d.normalize();if(!d.id.isBlank())definitions.put(d.id,d);}}catch(Exception ex){JsonStorage.archiveBrokenFile(file);}}for(Path file:JsonStorage.listJsonFiles(playerFolder)){try{UUID id=UUID.fromString(StoragePaths.fileBaseName(file));KitPlayerData p=JsonStorage.read(GSON,file,KitPlayerData.class);if(p!=null){p.normalize();players.put(id,p);}}catch(Exception ex){JsonStorage.archiveBrokenFile(file);}}}catch(IOException ex){SimpleServerUtilities.LOGGER.error("Failed to load kits.",ex);}}
 public synchronized void save(){for(KitDefinition d:definitions.values())saveDefinition(d);for(var e:players.entrySet())savePlayer(e.getKey(),e.getValue());}
 public synchronized void clearRuntime(){server=null;}
 public synchronized List<KitDefinition> definitions(){ArrayList<KitDefinition> out=new ArrayList<>();for(KitDefinition d:definitions.values()){KitDefinition c=GSON.fromJson(GSON.toJson(d),KitDefinition.class);c.normalize();out.add(c);}out.sort(Comparator.comparing(d->d.displayName,String.CASE_INSENSITIVE_ORDER));return List.copyOf(out);}
 public synchronized KitDefinition definition(String id){KitDefinition d=definitions.get(normalizeId(id));if(d==null)return null;KitDefinition c=GSON.fromJson(GSON.toJson(d),KitDefinition.class);c.normalize();return c;}
 public synchronized KitDefinition create(String id,String name){String key=normalizeId(id);if(key.isBlank())throw new IllegalArgumentException("Kit ID is required.");if(definitions.containsKey(key))throw new IllegalArgumentException("That kit already exists.");KitDefinition d=new KitDefinition();d.id=key;d.displayName=name;d.permissionKey="ssu.kits."+key;d.normalize();definitions.put(key,d);saveDefinition(d);return definition(key);}
 public synchronized void update(KitDefinition input){if(input==null)throw new IllegalArgumentException("Kit data is missing.");input.normalize();if(input.id.isBlank())throw new IllegalArgumentException("Kit ID is required.");definitions.put(input.id,input);saveDefinition(input);}
 public synchronized boolean delete(String id){KitDefinition d=definitions.remove(normalizeId(id));if(d==null)return false;try{Files.deleteIfExists(StoragePaths.jsonFile(definitionFolder,d.id));}catch(IOException ex){SimpleServerUtilities.LOGGER.warn("Failed to delete kit {}.",d.id,ex);}return true;}
 public synchronized void setItems(String id,List<ItemStack> stacks,net.minecraft.core.HolderLookup.Provider registries){KitDefinition d=definitions.get(normalizeId(id));if(d==null)throw new IllegalArgumentException("Unknown kit.");ArrayList<JsonElement> encoded=new ArrayList<>();for(int i=0;i<9;i++)encoded.add(i<stacks.size()?NpcItemCodec.encode(registries,stacks.get(i)):JsonNull.INSTANCE);d.items=encoded;d.normalize();saveDefinition(d);}
 public synchronized List<ItemStack> items(String id,net.minecraft.core.HolderLookup.Provider registries){KitDefinition d=definitions.get(normalizeId(id));if(d==null)return List.of();ArrayList<ItemStack> result=new ArrayList<>();for(JsonElement e:d.items)result.add(NpcItemCodec.decode(registries,e,"",1));return List.copyOf(result);}
 public synchronized List<KitDefinition> visible(ServerPlayer player){return definitions().stream().filter(d->d.enabled).filter(d->d.permissionKey.isBlank()||PermissionService.getBoolean(player,d.permissionKey,false)).toList();}
 public synchronized long remainingSeconds(ServerPlayer player,String kitId){KitDefinition d=definitions.get(normalizeId(kitId));if(d==null)return 0L;KitPlayerData data=players.get(player.getUUID());long last=data==null?0L:data.lastClaims.getOrDefault(d.id,0L);long available=last+d.cooldownSeconds*1000L;return Math.max(0L,(available-System.currentTimeMillis()+999L)/1000L);}
 public synchronized boolean claimed(ServerPlayer player,String kitId){KitPlayerData data=players.get(player.getUUID());return data!=null&&data.lastClaims.containsKey(normalizeId(kitId));}
 public String claim(ServerPlayer player,String rawId){if(!SimpleServerUtilities.CORE.modules().isActive("kits"))throw new IllegalArgumentException("Kits are disabled.");if(!PermissionService.getBoolean(player,be.winnetrie.mod.simpleserverutilities.permission.PermissionKeys.KITS_USE,true))throw new IllegalArgumentException("Kit access denied.");KitDefinition d;List<ItemStack> stacks;long now=System.currentTimeMillis();synchronized(this){d=definitions.get(normalizeId(rawId));if(d==null||!d.enabled)throw new IllegalArgumentException("That kit is unavailable.");if(d.locked)throw new IllegalArgumentException("That kit is currently locked.");if(!d.permissionKey.isBlank()&&!PermissionService.getBoolean(player,d.permissionKey,false))throw new IllegalArgumentException("You do not have access to that kit.");KitPlayerData data=players.computeIfAbsent(player.getUUID(),i->new KitPlayerData());if(d.oneTime&&data.lastClaims.containsKey(d.id))throw new IllegalArgumentException("That one-time kit has already been claimed.");long remaining=Math.max(0L,data.lastClaims.getOrDefault(d.id,0L)+d.cooldownSeconds*1000L-now);if(remaining>0L)throw new IllegalArgumentException("Kit cooldown: "+((remaining+999L)/1000L)+" seconds remaining.");stacks=items(d.id,player.level().registryAccess());if(!canFit(player,stacks))throw new IllegalArgumentException("Your inventory does not have enough room.");}
  if(d.priceMinor>0L){if(!SimpleServerUtilities.CORE.modules().isActive("economy"))throw new IllegalArgumentException("This kit has a price, but Economy is disabled.");EconomyResult result=SimpleServerUtilities.ECONOMY.debitTyped(player.getUUID(),player.getName().getString(),player.getUUID(),d.priceMinor,EconomyTransactionType.KIT_PURCHASE,"kits","Kit: "+d.displayName,"kit:"+d.id+":"+player.getUUID()+":"+now);if(!result.successful())throw new IllegalArgumentException(result.message());}
  for(ItemStack stack:stacks)if(!stack.isEmpty())player.getInventory().add(stack.copy());player.getInventory().setChanged();player.containerMenu.broadcastChanges();synchronized(this){KitPlayerData data=players.computeIfAbsent(player.getUUID(),i->new KitPlayerData());data.lastKnownName=player.getName().getString();data.lastClaims.put(d.id,now);savePlayer(player.getUUID(),data);}return "Claimed kit "+d.displayName+".";
 }
 private static boolean canFit(ServerPlayer p,List<ItemStack> stacks){ArrayList<ItemStack> simulated=new ArrayList<>();for(int i=0;i<36;i++)simulated.add(p.getInventory().getItem(i).copy());for(ItemStack source:stacks){if(source.isEmpty())continue;int left=source.getCount();for(ItemStack slot:simulated){if(left<=0)break;if(!slot.isEmpty()&&ItemStack.isSameItemSameComponents(slot,source)){int room=Math.max(0,slot.getMaxStackSize()-slot.getCount());int moved=Math.min(room,left);slot.grow(moved);left-=moved;}}for(int i=0;i<simulated.size()&&left>0;i++){if(simulated.get(i).isEmpty()){ItemStack placed=source.copy();int count=Math.min(left,placed.getMaxStackSize());placed.setCount(count);simulated.set(i,placed);left-=count;}}if(left>0)return false;}return true;}
 private synchronized void saveDefinition(KitDefinition d){if(definitionFolder!=null){d.normalize();definitionsStore.queueJson(GSON,StoragePaths.jsonFile(definitionFolder,d.id),d);}}
 private synchronized void savePlayer(UUID id,KitPlayerData d){if(playerFolder!=null){d.normalize();playersStore.queueJson(GSON,StoragePaths.jsonFile(playerFolder,id.toString()),d);}}
 private static String normalizeId(String id){return id==null?"":id.trim().toLowerCase(java.util.Locale.ROOT).replaceAll("[^a-z0-9._-]","_");}
}
