package be.winnetrie.mod.simpleserverutilities.kits;
import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;import com.google.gson.Gson;import com.google.gson.GsonBuilder;
import be.winnetrie.mod.simpleserverutilities.SimpleServerUtilities;import be.winnetrie.mod.simpleserverutilities.network.KitActionPayload;import be.winnetrie.mod.simpleserverutilities.network.KitDataPayload;import be.winnetrie.mod.simpleserverutilities.network.KitRequestPayload;import be.winnetrie.mod.simpleserverutilities.permission.PermissionKeys;import be.winnetrie.mod.simpleserverutilities.permission.PermissionService;
import net.minecraft.server.level.ServerPlayer;import net.neoforged.neoforge.network.PacketDistributor;import net.neoforged.neoforge.network.handling.IPayloadContext;
public final class KitService{private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();private KitService(){}
 public static void request(KitRequestPayload p,IPayloadContext c){if(!(c.player() instanceof ServerPlayer player))return;if(!p.admin()&&!PermissionService.getBoolean(player,PermissionKeys.KITS_USE,true)){PacketDistributor.sendToPlayer(player,new KitDataPayload(false,"","[]","Kit access denied.",true,p.requestId()));return;}send(player,p.admin(),p.selectedId(),p.requestId(),"",false);}
 public static void action(KitActionPayload p,IPayloadContext c){if(!(c.player() instanceof ServerPlayer player))return;boolean admin=p.action().startsWith("admin_");if(admin&&!canAdmin(player)){send(player,true,p.kitId(),p.requestId(),"Kit administration denied.",true);return;}String notice;boolean error=false;String selected=p.kitId();try{switch(p.action()){
  case "claim"->notice=SimpleServerUtilities.KITS.claim(player,p.kitId());
  case "admin_create"->{KitDefinition input=GSON.fromJson(p.json(),KitDefinition.class);if(input==null)throw new IllegalArgumentException("Kit data is missing.");input.normalize();KitDefinition created=SimpleServerUtilities.KITS.create(input.id,input.displayName);input.id=created.id;if(input.permissionKey.isBlank())input.permissionKey="ssu.kits."+created.id;input.items=created.items;SimpleServerUtilities.KITS.update(input);selected=created.id;notice="Kit created.";}
  case "admin_save"->{KitDefinition input=GSON.fromJson(p.json(),KitDefinition.class);if(input==null)throw new IllegalArgumentException("Kit data is missing.");input.normalize();KitDefinition existing=SimpleServerUtilities.KITS.definition(input.id);if(existing==null)throw new IllegalArgumentException("Kit not found.");input.items=existing.items;SimpleServerUtilities.KITS.update(input);selected=input.id;notice="Kit settings saved.";}
  case "admin_delete"->{if(!SimpleServerUtilities.KITS.delete(p.kitId()))throw new IllegalArgumentException("Kit not found.");selected="";notice="Kit deleted.";}
  case "admin_open_contents"->{if(!KitEditorService.open(player,p.kitId()))throw new IllegalArgumentException("Kit not found.");return;}
  default->throw new IllegalArgumentException("Unknown kit action.");}
 }catch(Exception ex){notice=ex.getMessage()==null?"Kit action failed safely.":ex.getMessage();error=true;}if(admin&&!error)SimpleServerUtilities.SERVER_OPERATIONS.audit(player,"kits."+p.action(),selected,"");send(player,admin,selected,p.requestId(),notice,error);}
 public static void send(ServerPlayer player,boolean admin,String selected,long request,String notice,boolean error){if(!admin&&!PermissionService.getBoolean(player,PermissionKeys.KITS_USE,true)){PacketDistributor.sendToPlayer(player,new KitDataPayload(false,"","[]","Kit access denied.",true,request));return;}if(admin&&!canAdmin(player)){PacketDistributor.sendToPlayer(player,new KitDataPayload(true,"","[]","Kit administration denied.",true,request));return;}List<KitDefinition> defs=admin?SimpleServerUtilities.KITS.definitions():SimpleServerUtilities.KITS.visible(player);ArrayList<Map<String,Object>> rows=new ArrayList<>();for(KitDefinition d:defs){Map<String,Object> row=new LinkedHashMap<>();row.put("definition",d);row.put("remainingSeconds",admin?0L:SimpleServerUtilities.KITS.remainingSeconds(player,d.id));row.put("claimed",admin?false:SimpleServerUtilities.KITS.claimed(player,d.id));row.put("items",SimpleServerUtilities.KITS.items(d.id,player.level().registryAccess()).stream().map(stack->stack.isEmpty()?"":net.minecraft.core.registries.BuiltInRegistries.ITEM.getKey(stack.getItem()).toString()+" x"+stack.getCount()).toList());rows.add(row);}PacketDistributor.sendToPlayer(player,new KitDataPayload(admin,selected,GSON.toJson(rows),notice,error,request));}
 private static boolean canAdmin(ServerPlayer p){return PermissionService.isAdmin(p)&&PermissionService.getBoolean(p,PermissionKeys.KITS_ADMIN,false);}
}
