package be.winnetrie.mod.simpleserverutilities.moderation;

import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Locale;import java.util.Map;
import be.winnetrie.mod.simpleserverutilities.minigame.MinigamePlayerState;
/** Persistent punishment state for one jailed player. Physical facilities live in the dedicated Jails module. */
public final class JailSentence {
    public static final int SCHEMA_VERSION=2; public int schemaVersion=SCHEMA_VERSION;
    public boolean active; public String jailId=""; public String reason=""; public long startedAt;
    /** CHOICE, TASK_ONLY or TIME_ONLY. */ public String sentenceMode="TASK_ONLY";
    /** PENDING, TASK or TIME. A successful BUYOUT releases immediately and is not persisted as an active path. */ public String selectedPath="TASK";
    public long choiceExpiresAt; public long taskDeadlineAt; public long releaseAt; public long buyoutMinor;
    public int assignedCell=-1; public boolean failedPunishment; public long failedAt; public boolean restorePending; public String releaseReason="";
    /** Legacy dev3.12 field retained only so old saves deserialize safely. */ public String taskRegion="";
    public Map<String,Integer> requirements=new LinkedHashMap<>(); public Map<String,Integer> progress=new LinkedHashMap<>(); public List<String> toolItems=new ArrayList<>(); public int rewardLookbackDays=30; public MinigamePlayerState inventoryBackup;
    public void normalize(){int previous=schemaVersion;schemaVersion=SCHEMA_VERSION;jailId=bound(jailId,64);reason=bound(reason,8192);startedAt=Math.max(0L,startedAt);choiceExpiresAt=Math.max(0L,choiceExpiresAt);taskDeadlineAt=Math.max(0L,taskDeadlineAt);releaseAt=Math.max(0L,releaseAt);buyoutMinor=Math.max(0L,buyoutMinor);failedAt=Math.max(0L,failedAt);releaseReason=bound(releaseReason,1024);assignedCell=Math.max(-1,Math.min(31,assignedCell));taskRegion=bound(taskRegion,64);rewardLookbackDays=Math.max(1,Math.min(365,rewardLookbackDays));if(requirements==null)requirements=new LinkedHashMap<>();if(progress==null)progress=new LinkedHashMap<>();if(toolItems==null)toolItems=new ArrayList<>();requirements=clean(requirements);progress=clean(progress);ArrayList<String> tools=new ArrayList<>();for(String tool:toolItems){if(tools.size()>=9)break;String s=bound(tool,128).trim();if(!s.isBlank())tools.add(s);}toolItems=tools;if(previous<2&&active){sentenceMode=!requirements.isEmpty()?"TASK_ONLY":"TIME_ONLY";selectedPath=!requirements.isEmpty()?"TASK":"TIME";choiceExpiresAt=0L;taskDeadlineAt=0L;}sentenceMode=switch(sentenceMode==null?"TASK_ONLY":sentenceMode.trim().toUpperCase(Locale.ROOT)){case"CHOICE"->"CHOICE";case"TIME_ONLY"->"TIME_ONLY";default->"TASK_ONLY";};selectedPath=switch(selectedPath==null?"TASK":selectedPath.trim().toUpperCase(Locale.ROOT)){case"PENDING"->"PENDING";case"TIME"->"TIME";default->"TASK";};if(sentenceMode.equals("TIME_ONLY"))selectedPath="TIME";if(sentenceMode.equals("TASK_ONLY"))selectedPath="TASK";if(inventoryBackup!=null)inventoryBackup.normalize();}
    public boolean pendingChoice(){return active&&"PENDING".equals(selectedPath);} public boolean taskSelected(){return active&&"TASK".equals(selectedPath);} public boolean timeSelected(){return active&&"TIME".equals(selectedPath);} public boolean timed(){return timeSelected()&&releaseAt>0L;} public boolean hasTask(){return active&&!requirements.isEmpty();} public boolean taskComplete(){if(!hasTask())return false;for(var e:requirements.entrySet())if(progress.getOrDefault(e.getKey(),0)<e.getValue())return false;return true;} public long choiceSeconds(long now){return pendingChoice()?Math.max(0L,(choiceExpiresAt-now+999L)/1000L):0L;} public long taskSeconds(long now){return taskSelected()&&taskDeadlineAt>0L?Math.max(0L,(taskDeadlineAt-now+999L)/1000L):0L;}
    private static Map<String,Integer> clean(Map<String,Integer> in){LinkedHashMap<String,Integer> out=new LinkedHashMap<>();for(var e:in.entrySet()){if(out.size()>=16)break;String k=bound(e.getKey(),128).trim();int v=e.getValue()==null?0:Math.max(0,Math.min(1_000_000,e.getValue()));if(!k.isBlank()&&v>0)out.put(k,v);}return out;}private static String bound(String v,int m){String s=v==null?"":v;return s.length()>m?s.substring(0,m):s;}
}
