package be.winnetrie.mod.simpleserverutilities.moderation;

import java.lang.reflect.Type;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;import java.util.UUID;import com.google.gson.Gson;import com.google.gson.GsonBuilder;import com.google.gson.reflect.TypeToken;
import be.winnetrie.mod.simpleserverutilities.SimpleServerUtilities;import be.winnetrie.mod.simpleserverutilities.jail.JailDefinition;import be.winnetrie.mod.simpleserverutilities.network.JailDashboardActionPayload;import be.winnetrie.mod.simpleserverutilities.network.JailDashboardPayload;import be.winnetrie.mod.simpleserverutilities.network.PlayerInventoryOpenPayload;import be.winnetrie.mod.simpleserverutilities.network.PlayerManagementActionPayload;import be.winnetrie.mod.simpleserverutilities.network.PlayerManagementDataPayload;import be.winnetrie.mod.simpleserverutilities.network.PlayerManagementRequestPayload;import be.winnetrie.mod.simpleserverutilities.permission.PermissionKeys;import be.winnetrie.mod.simpleserverutilities.permission.PermissionService;import net.minecraft.server.level.ServerPlayer;import net.neoforged.neoforge.network.PacketDistributor;import net.neoforged.neoforge.network.handling.IPayloadContext;
/** Network boundary for moderation plus prisoner dashboard actions. Physical jail setup is handled by JailService. */
public final class ModerationService{
 private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();private static final Type INT_MAP=new TypeToken<Map<String,Integer>>(){}.getType();private static final Type STRING_LIST=new TypeToken<List<String>>(){}.getType();private ModerationService(){}
 public static void request(PlayerManagementRequestPayload p,IPayloadContext c){if(c.player() instanceof ServerPlayer actor)send(actor,p.target(),p.requestId(),"",false);}
 public static void action(PlayerManagementActionPayload p,IPayloadContext c){if(!(c.player() instanceof ServerPlayer actor))return;if(!canAdmin(actor)){send(actor,p.target(),p.requestId(),"Moderation administration denied.",true);return;}String notice;boolean error=false;try{UUID id=SimpleServerUtilities.MODERATION.resolvePlayer(p.target());String a=p.action().trim().toLowerCase(java.util.Locale.ROOT);if(id==null&&!a.startsWith("whitelist")&&!a.startsWith("set_jail"))throw new IllegalArgumentException("Player name or UUID was not found.");switch(a){
  case"warn"->{SimpleServerUtilities.MODERATION.warn(actor,id,p.reason(),p.warningSeconds());notice="Warning sent.";}case"kick"->{SimpleServerUtilities.MODERATION.kick(actor,id,p.reason());notice="Player kicked.";}case"ban_temp"->{SimpleServerUtilities.MODERATION.ban(actor,id,p.reason(),Math.max(1L,p.durationSeconds()));notice="Temporary ban applied.";}case"ban_permanent"->{SimpleServerUtilities.MODERATION.ban(actor,id,p.reason(),0L);notice="Permanent ban applied.";}case"unban"->{SimpleServerUtilities.MODERATION.unban(actor,id);notice="Player unbanned.";}case"freeze"->{SimpleServerUtilities.MODERATION.setFrozen(actor,id,true,p.reason());notice="Player frozen.";}case"unfreeze"->{SimpleServerUtilities.MODERATION.setFrozen(actor,id,false,p.reason());notice="Player unfrozen.";}
  case"jail"->{Map<String,Integer> requirements=GSON.fromJson(p.requirementsJson(),INT_MAP);List<String> tools=GSON.fromJson(p.toolsJson(),STRING_LIST);SimpleServerUtilities.MODERATION.jail(actor,id,p.reason(),p.taskRegion(),p.sentenceMode(),p.durationSeconds(),p.taskDeadlineSeconds(),p.buyoutMinor(),requirements,tools,p.lookbackDays());notice="Player jailed and moved to the selected facility.";}
  case"unjail"->{SimpleServerUtilities.MODERATION.release(id,p.reason().isBlank()?"Released by an administrator.":p.reason(),actor);notice="Player released.";}case"jail_tp_to"->{if(!SimpleServerUtilities.MODERATION.jailed(id))throw new IllegalArgumentException("That player is not currently jailed.");ServerPlayer prisoner=actor.level().getServer().getPlayerList().getPlayer(id);if(prisoner==null)throw new IllegalArgumentException("That prisoner is not online.");actor.teleportTo(prisoner.level(),prisoner.getX(),prisoner.getY(),prisoner.getZ(),java.util.Set.of(),prisoner.getYRot(),prisoner.getXRot(),true);notice="Teleported to prisoner.";}
  case"set_jail_location"->{SimpleServerUtilities.MODERATION.setJailLocation(actor);notice="Legacy jail fallback location set.";}case"clear_jail_location"->{SimpleServerUtilities.MODERATION.clearJailLocation();notice="Legacy jail fallback cleared.";}
  case"whitelist_enable"->{SimpleServerUtilities.MODERATION.setWhitelistEnabled(true);notice="Whitelist enabled.";}case"whitelist_disable"->{SimpleServerUtilities.MODERATION.setWhitelistEnabled(false);notice="Whitelist disabled.";}case"whitelist_add"->{SimpleServerUtilities.MODERATION.addWhitelist(p.taskRegion());notice="Whitelist entry added.";}case"whitelist_remove"->{if(!SimpleServerUtilities.MODERATION.removeWhitelist(p.taskRegion()))throw new IllegalArgumentException("Whitelist entry not found.");notice="Whitelist entry removed.";}default->throw new IllegalArgumentException("Unknown moderation action.");}
 }catch(Exception ex){notice=ex.getMessage()==null?"Moderation action failed safely.":ex.getMessage();error=true;}if(!error)SimpleServerUtilities.SERVER_OPERATIONS.audit(actor,"moderation."+p.action(),p.target(),p.reason());send(actor,p.target(),p.requestId(),notice,error);}
 public static void jailAction(JailDashboardActionPayload p,IPayloadContext c){if(!(c.player() instanceof ServerPlayer player))return;String notice="";boolean error=false;try{switch(p.action().trim().toLowerCase(java.util.Locale.ROOT)){case"buyout"->{var result=SimpleServerUtilities.MODERATION.buyout(player);if(!result.successful())throw new IllegalArgumentException(result.message());notice=result.message();}case"task"->{SimpleServerUtilities.MODERATION.selectTask(player,false);notice="Task punishment selected.";}case"complete"->{SimpleServerUtilities.MODERATION.completeTask(player);notice="Task punishment completed.";}case"open"->{}default->throw new IllegalArgumentException("Unknown jail action.");}}catch(Exception ex){notice=ex.getMessage()==null?"Jail action failed safely.":ex.getMessage();error=true;}sendJail(player,notice,error);}
 public static void openInventory(PlayerInventoryOpenPayload p,IPayloadContext c){if(!(c.player() instanceof ServerPlayer actor))return;if(!PermissionService.isAdmin(actor)||!PermissionService.getBoolean(actor,PermissionKeys.MODERATION_INVENTORY,false)){actor.sendSystemMessage(net.minecraft.network.chat.Component.literal("Player inventory administration denied."));return;}PlayerInventoryAdminService.open(actor,p.target(),p.mode());}
 public static void sendJail(ServerPlayer player,String notice,boolean error){PlayerModerationRecord r=SimpleServerUtilities.MODERATION.record(player.getUUID());Map<String,Object> view=new LinkedHashMap<>();if(r!=null&&r.jail!=null){JailSentence j=r.jail;JailDefinition facility=SimpleServerUtilities.JAILS.definition(j.jailId);view.put("active",j.active);view.put("jailId",j.jailId);view.put("jailName",facility==null?j.jailId:facility.displayName);view.put("reason",j.reason);view.put("startedAt",j.startedAt);view.put("sentenceMode",j.sentenceMode);view.put("selectedPath",j.selectedPath);view.put("choiceExpiresAt",j.choiceExpiresAt);view.put("taskDeadlineAt",j.taskDeadlineAt);view.put("releaseAt",j.releaseAt);view.put("buyoutMinor",j.buyoutMinor);view.put("buyoutFormatted",SimpleServerUtilities.ECONOMY.format(j.buyoutMinor));view.put("balanceMinor",SimpleServerUtilities.ECONOMY.balance(player));view.put("balanceFormatted",SimpleServerUtilities.ECONOMY.format(SimpleServerUtilities.ECONOMY.balance(player)));view.put("requirements",j.requirements);view.put("progress",j.progress);view.put("complete",j.taskComplete());view.put("assignedCell",j.assignedCell);}PacketDistributor.sendToPlayer(player,new JailDashboardPayload(GSON.toJson(view),notice,error));}
 private static void send(ServerPlayer actor,String target,long request,String notice,boolean error){if(!canAdmin(actor)){PacketDistributor.sendToPlayer(actor,new PlayerManagementDataPayload(target,"{}","Moderation administration denied.",true,request));return;}UUID id=SimpleServerUtilities.MODERATION.resolvePlayer(target);Map<String,Object> view=new LinkedHashMap<>();if(id!=null){PlayerModerationRecord r=SimpleServerUtilities.MODERATION.record(id);ServerPlayer online=actor.level().getServer().getPlayerList().getPlayer(id);view.put("uuid",id.toString());view.put("name",r==null?(online==null?target:online.getName().getString()):r.lastKnownName);view.put("online",online!=null);view.put("banned",r!=null&&r.banActive(System.currentTimeMillis()));view.put("permanentBan",r!=null&&r.permanentBan);view.put("banExpiresAt",r==null?0L:r.banExpiresAt);view.put("banReason",r==null?"":r.banReason);view.put("frozen",r!=null&&r.frozen);view.put("jail",r==null?new JailSentence():r.jail);view.put("history",r==null?List.of():r.history);view.put("knownNames",r==null?List.of():r.knownNames);view.put("lastSeenAt",r==null?0L:r.lastSeenAt);view.put("whitelisted",SimpleServerUtilities.MODERATION.whitelisted(id,r==null?target:r.lastKnownName));}
  ModerationSettings settings=SimpleServerUtilities.MODERATION.settingsCopy();view.put("whitelistEnabled",settings.whitelistEnabled);view.put("whitelist",settings.whitelist);view.put("jailLocation",settings.jailLocation);view.put("defaultWarningSeconds",settings.defaultWarningSeconds);view.put("jails",SimpleServerUtilities.JAILS.definitions());PacketDistributor.sendToPlayer(actor,new PlayerManagementDataPayload(target,GSON.toJson(view),notice,error,request));}
 private static boolean canAdmin(ServerPlayer p){return PermissionService.isAdmin(p)&&PermissionService.getBoolean(p,PermissionKeys.MODERATION_ADMIN,false);}
}
